# Programming Assignment 1 
## (RS Codes and List Decoding of RS Codes)

## Import Libraries

In [145]:
import numpy as np
import math 
from sympy import *
from sympy.abc import x,y,X,Y
import random
import sys
import pandas as pd

# Question 1

## Define Functions

In [36]:
def pol_gen(coeff_vect):
    pl = 0
    d = len(coeff_vect)-1
    for i in range(0,len(coeff_vect)):
        pl = (pl + int(coeff_vect[d-i])*x**i)
    return pl

def all_coeff_gen(d):
    all_coeff = np.zeros((2**(d+1),d+1))
    for i in range(0,2**(d+1)): 
        t = i
        for j in range (0,d+1):
            all_coeff[i][d-j]= t%2
            t = int(t/2)
    return all_coeff

def mod2_pol(pol):
    if(pol==0):
        return pol_gen([0])
    else:
        d = degree(pol)
        coeff_vect = np.zeros((d+1,1))
        for i in range(0,d):
            qx,rx = div(pol,x**(d-i))
            coeff_vect[i] = qx%2
            pol = pol - qx*x**(d-i)
        coeff_vect[d] = pol%2
        return pol_gen(coeff_vect)

## Part (a)

In [37]:
# Finding all irreducible polynomial of degree 8 over F2 (Hit and trial)
d=8

# Generating all polynomials upto degree 7
all_coeff = all_coeff_gen(d-1)

print("All irreducible polynomial of degree 8 over F2:")
for i in range(0,2**d):
    flag = 0
    
    # Check for all possible monic polynomials of degree 8 whether they are irreducible or not 
    sx = x**d + pol_gen(all_coeff[i])

    # Check for any factors
    # Check for all polynomials upto degree 7 (8-1) 
    # 0,1 are not to be taken as factors that's why loop starts from 2 (1+x)        
    for j in range (2,2**d): 
        qx,rx= div(sx,pol_gen(all_coeff[j]))
        rx = mod2_pol(rx)  
        
        # If there exist any factor then the polynomial is reducible  
        if(rx==0):
            flag = 1
            break 
            
    # If there were no factors then the polynomial is irreducible 
    if(flag==0):
        print(sx)

All irreducible polynomial of degree 8 over F2:
x**8 + x**4 + x**3 + x + 1
x**8 + x**4 + x**3 + x**2 + 1
x**8 + x**5 + x**3 + x + 1
x**8 + x**5 + x**3 + x**2 + 1
x**8 + x**5 + x**4 + x**3 + 1
x**8 + x**5 + x**4 + x**3 + x**2 + x + 1
x**8 + x**6 + x**3 + x**2 + 1
x**8 + x**6 + x**4 + x**3 + x**2 + x + 1
x**8 + x**6 + x**5 + x + 1
x**8 + x**6 + x**5 + x**2 + 1
x**8 + x**6 + x**5 + x**3 + 1
x**8 + x**6 + x**5 + x**4 + 1
x**8 + x**6 + x**5 + x**4 + x**2 + x + 1
x**8 + x**6 + x**5 + x**4 + x**3 + x + 1
x**8 + x**7 + x**2 + x + 1
x**8 + x**7 + x**3 + x + 1
x**8 + x**7 + x**3 + x**2 + 1
x**8 + x**7 + x**4 + x**3 + x**2 + x + 1
x**8 + x**7 + x**5 + x + 1
x**8 + x**7 + x**5 + x**3 + 1
x**8 + x**7 + x**5 + x**4 + 1
x**8 + x**7 + x**5 + x**4 + x**3 + x**2 + 1
x**8 + x**7 + x**6 + x + 1
x**8 + x**7 + x**6 + x**3 + x**2 + x + 1
x**8 + x**7 + x**6 + x**4 + x**2 + x + 1
x**8 + x**7 + x**6 + x**4 + x**3 + x**2 + 1
x**8 + x**7 + x**6 + x**5 + x**2 + x + 1
x**8 + x**7 + x**6 + x**5 + x**4 + x + 1
x**8 + x**7 + x**6 + x**5 + x**4 + x**2 + 1
x**8 + x**7 + x**6 + x**5 + x**4 + x**3 + 1

## Part (b)

In [38]:
# Finite field F2 defined using the following Irreducible polynomial:
sx = x**8 + x**4 + x**3 + x**2 + 1 
# Chose the particular irreducible polynomial as it leads to a simple expression for primitve element 

F2_8 = {}

# Generate F2_8 (set of all polynomimals over F2 modulo sx 
# basically set of all polynomials over F2 of degree upto 7)
all_coeff = all_coeff_gen(8-1)
for i in range(0,2**d):
    F2_8[i] = pol_gen(all_coeff[i])

print("GF(2^8)")    
F2_8

GF(2^8)

{0: 0,
 1: 1,
 2: x,
 3: x + 1,
 4: x**2,
 5: x**2 + 1,
 6: x**2 + x,
 7: x**2 + x + 1,
 8: x**3,
 9: x**3 + 1,
 10: x**3 + x,
 11: x**3 + x + 1,
 12: x**3 + x**2,
 13: x**3 + x**2 + 1,
 14: x**3 + x**2 + x,
 15: x**3 + x**2 + x + 1,
 16: x**4,
 17: x**4 + 1,
 18: x**4 + x,
 19: x**4 + x + 1,
 20: x**4 + x**2,
 21: x**4 + x**2 + 1,
 22: x**4 + x**2 + x,
 23: x**4 + x**2 + x + 1,
 24: x**4 + x**3,
 25: x**4 + x**3 + 1,
 26: x**4 + x**3 + x,
 27: x**4 + x**3 + x + 1,
 28: x**4 + x**3 + x**2,
 29: x**4 + x**3 + x**2 + 1,
 30: x**4 + x**3 + x**2 + x,
 31: x**4 + x**3 + x**2 + x + 1,
 32: x**5,
 33: x**5 + 1,
 34: x**5 + x,
 35: x**5 + x + 1,
 36: x**5 + x**2,
 37: x**5 + x**2 + 1,
 38: x**5 + x**2 + x,
 39: x**5 + x**2 + x + 1,
 40: x**5 + x**3,
 41: x**5 + x**3 + 1,
 42: x**5 + x**3 + x,
 43: x**5 + x**3 + x + 1,
 44: x**5 + x**3 + x**2,
 45: x**5 + x**3 + x**2 + 1,
 46: x**5 + x**3 + x**2 + x,
 47: x**5 + x**3 + x**2 + x + 1,
 48: x**5 + x**4,
 49: x**5 + x**4 + 1,
 50: x**5 + x**4 + x,
 51: x**5 + x**4 + x + 1,
 52: x**5 + x**4 + x**2,
 53: x**5 + x**4 + x**2 + 1,
 54: x**5 + x**4 + x**2 + x,
 55: x**5 + x**4 + x**2 + x + 1,
 56: x**5 + x**4 + x**3,
 57: x**5 + x**4 + x**3 + 1,
 58: x**5 + x**4 + x**3 + x,
 59: x**5 + x**4 + x**3 + x + 1,
 60: x**5 + x**4 + x**3 + x**2,
 61: x**5 + x**4 + x**3 + x**2 + 1,
 62: x**5 + x**4 + x**3 + x**2 + x,
 63: x**5 + x**4 + x**3 + x**2 + x + 1,
 64: x**6,
 65: x**6 + 1,
 66: x**6 + x,
 67: x**6 + x + 1,
 68: x**6 + x**2,
 69: x**6 + x**2 + 1,
 70: x**6 + x**2 + x,
 71: x**6 + x**2 + x + 1,
 72: x**6 + x**3,
 73: x**6 + x**3 + 1,
 74: x**6 + x**3 + x,
 75: x**6 + x**3 + x + 1,
 76: x**6 + x**3 + x**2,
 77: x**6 + x**3 + x**2 + 1,
 78: x**6 + x**3 + x**2 + x,
 79: x**6 + x**3 + x**2 + x + 1,
 80: x**6 + x**4,
 81: x**6 + x**4 + 1,
 82: x**6 + x**4 + x,
 83: x**6 + x**4 + x + 1,
 84: x**6 + x**4 + x**2,
 85: x**6 + x**4 + x**2 + 1,
 86: x**6 + x**4 + x**2 + x,
 87: x**6 + x**4 + x**2 + x + 1,
 88: x**6 + x**4 + x**3,
 89: x**6 + x**4 + x**3 + 1,
 90: x**6 + x**4 + x**3 + x,
 91: x**6 + x**4 + x**3 + x + 1,
 92: x**6 + x**4 + x**3 + x**2,
 93: x**6 + x**4 + x**3 + x**2 + 1,
 94: x**6 + x**4 + x**3 + x**2 + x,
 95: x**6 + x**4 + x**3 + x**2 + x + 1,
 96: x**6 + x**5,
 97: x**6 + x**5 + 1,
 98: x**6 + x**5 + x,
 99: x**6 + x**5 + x + 1,
 100: x**6 + x**5 + x**2,
 101: x**6 + x**5 + x**2 + 1,
 102: x**6 + x**5 + x**2 + x,
 103: x**6 + x**5 + x**2 + x + 1,
 104: x**6 + x**5 + x**3,
 105: x**6 + x**5 + x**3 + 1,
 106: x**6 + x**5 + x**3 + x,
 107: x**6 + x**5 + x**3 + x + 1,
 108: x**6 + x**5 + x**3 + x**2,
 109: x**6 + x**5 + x**3 + x**2 + 1,
 110: x**6 + x**5 + x**3 + x**2 + x,
 111: x**6 + x**5 + x**3 + x**2 + x + 1,
 112: x**6 + x**5 + x**4,
 113: x**6 + x**5 + x**4 + 1,
 114: x**6 + x**5 + x**4 + x,
 115: x**6 + x**5 + x**4 + x + 1,
 116: x**6 + x**5 + x**4 + x**2,
 117: x**6 + x**5 + x**4 + x**2 + 1,
 118: x**6 + x**5 + x**4 + x**2 + x,
 119: x**6 + x**5 + x**4 + x**2 + x + 1,
 120: x**6 + x**5 + x**4 + x**3,
 121: x**6 + x**5 + x**4 + x**3 + 1,
 122: x**6 + x**5 + x**4 + x**3 + x,
 123: x**6 + x**5 + x**4 + x**3 + x + 1,
 124: x**6 + x**5 + x**4 + x**3 + x**2,
 125: x**6 + x**5 + x**4 + x**3 + x**2 + 1,
 126: x**6 + x**5 + x**4 + x**3 + x**2 + x,
 127: x**6 + x**5 + x**4 + x**3 + x**2 + x + 1,
 128: x**7,
 129: x**7 + 1,
 130: x**7 + x,
 131: x**7 + x + 1,
 132: x**7 + x**2,
 133: x**7 + x**2 + 1,
 134: x**7 + x**2 + x,
 135: x**7 + x**2 + x + 1,
 136: x**7 + x**3,
 137: x**7 + x**3 + 1,
 138: x**7 + x**3 + x,
 139: x**7 + x**3 + x + 1,
 140: x**7 + x**3 + x**2,
 141: x**7 + x**3 + x**2 + 1,
 142: x**7 + x**3 + x**2 + x,
 143: x**7 + x**3 + x**2 + x + 1,
 144: x**7 + x**4,
 145: x**7 + x**4 + 1,
 146: x**7 + x**4 + x,
 147: x**7 + x**4 + x + 1,
 148: x**7 + x**4 + x**2,
 149: x**7 + x**4 + x**2 + 1,
 150: x**7 + x**4 + x**2 + x,
 151: x**7 + x**4 + x**2 + x + 1,
 152: x**7 + x**4 + x**3,
 153: x**7 + x**4 + x**3 + 1,
 154: x**7 + x**4 + x**3 + x,
 155: x**7 + x**4 + x**3 + x + 1,
 156: x**7 + x**4 + x**3 + x**2,
 157: x**7 + x**4 + x**3 + x**2 + 1,
 158: x**7 + x**4 + x**3 + x**2 + x,
 159: x**7 + x**4 + x**3 + x**2 + x + 1,
 160: x**7 + x**5,
 161: x**7 + x**5 + 1,
 162: x**7 + x**5 + x,
 163: x**7 + x**5 + x + 1,
 164: x**7 + x**5 + x**2,
 165: x**7 + x**5 + x**2 + 1,
 166: x**7 + x**5 + x**2 + x,
 167: x**7 + x**5 + x**2 + x + 1,
 168: x**7 + x**5 + x**3,
 169: x**7 + x**5 + x**3 + 1,
 170: x**7 + x**5 + x**3 + x,
 171: x**7 + x**5 + x**3 + x + 1,
 172: x**7 + x**5 + x**3 + x**2,
 173: x**7 + x**5 + x**3 + x**2 + 1,
 174: x**7 + x**5 + x**3 + x**2 + x,
 175: x**7 + x**5 + x**3 + x**2 + x + 1,
 176: x**7 + x**5 + x**4,
 177: x**7 + x**5 + x**4 + 1,
 178: x**7 + x**5 + x**4 + x,
 179: x**7 + x**5 + x**4 + x + 1,
 180: x**7 + x**5 + x**4 + x**2,
 181: x**7 + x**5 + x**4 + x**2 + 1,
 182: x**7 + x**5 + x**4 + x**2 + x,
 183: x**7 + x**5 + x**4 + x**2 + x + 1,
 184: x**7 + x**5 + x**4 + x**3,
 185: x**7 + x**5 + x**4 + x**3 + 1,
 186: x**7 + x**5 + x**4 + x**3 + x,
 187: x**7 + x**5 + x**4 + x**3 + x + 1,
 188: x**7 + x**5 + x**4 + x**3 + x**2,
 189: x**7 + x**5 + x**4 + x**3 + x**2 + 1,
 190: x**7 + x**5 + x**4 + x**3 + x**2 + x,
 191: x**7 + x**5 + x**4 + x**3 + x**2 + x + 1,
 192: x**7 + x**6,
 193: x**7 + x**6 + 1,
 194: x**7 + x**6 + x,
 195: x**7 + x**6 + x + 1,
 196: x**7 + x**6 + x**2,
 197: x**7 + x**6 + x**2 + 1,
 198: x**7 + x**6 + x**2 + x,
 199: x**7 + x**6 + x**2 + x + 1,
 200: x**7 + x**6 + x**3,
 201: x**7 + x**6 + x**3 + 1,
 202: x**7 + x**6 + x**3 + x,
 203: x**7 + x**6 + x**3 + x + 1,
 204: x**7 + x**6 + x**3 + x**2,
 205: x**7 + x**6 + x**3 + x**2 + 1,
 206: x**7 + x**6 + x**3 + x**2 + x,
 207: x**7 + x**6 + x**3 + x**2 + x + 1,
 208: x**7 + x**6 + x**4,
 209: x**7 + x**6 + x**4 + 1,
 210: x**7 + x**6 + x**4 + x,
 211: x**7 + x**6 + x**4 + x + 1,
 212: x**7 + x**6 + x**4 + x**2,
 213: x**7 + x**6 + x**4 + x**2 + 1,
 214: x**7 + x**6 + x**4 + x**2 + x,
 215: x**7 + x**6 + x**4 + x**2 + x + 1,
 216: x**7 + x**6 + x**4 + x**3,
 217: x**7 + x**6 + x**4 + x**3 + 1,
 218: x**7 + x**6 + x**4 + x**3 + x,
 219: x**7 + x**6 + x**4 + x**3 + x + 1,
 220: x**7 + x**6 + x**4 + x**3 + x**2,
 221: x**7 + x**6 + x**4 + x**3 + x**2 + 1,
 222: x**7 + x**6 + x**4 + x**3 + x**2 + x,
 223: x**7 + x**6 + x**4 + x**3 + x**2 + x + 1,
 224: x**7 + x**6 + x**5,
 225: x**7 + x**6 + x**5 + 1,
 226: x**7 + x**6 + x**5 + x,
 227: x**7 + x**6 + x**5 + x + 1,
 228: x**7 + x**6 + x**5 + x**2,
 229: x**7 + x**6 + x**5 + x**2 + 1,
 230: x**7 + x**6 + x**5 + x**2 + x,
 231: x**7 + x**6 + x**5 + x**2 + x + 1,
 232: x**7 + x**6 + x**5 + x**3,
 233: x**7 + x**6 + x**5 + x**3 + 1,
 234: x**7 + x**6 + x**5 + x**3 + x,
 235: x**7 + x**6 + x**5 + x**3 + x + 1,
 236: x**7 + x**6 + x**5 + x**3 + x**2,
 237: x**7 + x**6 + x**5 + x**3 + x**2 + 1,
 238: x**7 + x**6 + x**5 + x**3 + x**2 + x,
 239: x**7 + x**6 + x**5 + x**3 + x**2 + x + 1,
 240: x**7 + x**6 + x**5 + x**4,
 241: x**7 + x**6 + x**5 + x**4 + 1,
 242: x**7 + x**6 + x**5 + x**4 + x,
 243: x**7 + x**6 + x**5 + x**4 + x + 1,
 244: x**7 + x**6 + x**5 + x**4 + x**2,
 245: x**7 + x**6 + x**5 + x**4 + x**2 + 1,
 246: x**7 + x**6 + x**5 + x**4 + x**2 + x,
 247: x**7 + x**6 + x**5 + x**4 + x**2 + x + 1,
 248: x**7 + x**6 + x**5 + x**4 + x**3,
 249: x**7 + x**6 + x**5 + x**4 + x**3 + 1,
 250: x**7 + x**6 + x**5 + x**4 + x**3 + x,
 251: x**7 + x**6 + x**5 + x**4 + x**3 + x + 1,
 252: x**7 + x**6 + x**5 + x**4 + x**3 + x**2,
 253: x**7 + x**6 + x**5 + x**4 + x**3 + x**2 + 1,
 254: x**7 + x**6 + x**5 + x**4 + x**3 + x**2 + x,
 255: x**7 + x**6 + x**5 + x**4 + x**3 + x**2 + x + 1}

In [39]:
# Find a primitive element in the above field (Primitive element has order q-1(=63)) (Excluding 0 and 1)
prim_el = 0
flag = 0
for i in range(2,2**d):
    if (flag == 0):
        for j in range (1,2**d):
            qx,rx=div((F2_8[i])**(j),sx)
            rx = mod2_pol(rx)
            if (rx == 1):
                if ( j!= 2**d-1):
                    break
                elif (j==2**d-1):
                    prim_el = F2_8[i]
                    flag = 1
    else: 
        print("Primitive element:", prim_el)
        break

Primitive element: x

In [40]:
# Elements need to be expressed in polynomial form

# Calculate prim_el**34 
qx,rx = div(prim_el**34,sx)
el_1 = mod2_pol(rx)

# Calculate prim_el**20 
qx,rx = div(prim_el**20,sx)
el_2 = mod2_pol(rx)

# Calculate product of prim_el**34 and prim_el**20
qx,rx = div(prim_el**34 * prim_el**20,sx)
el = mod2_pol(rx)

# Calculate prim_el**54
qx,rx = div(prim_el**54,sx)
el_3 = mod2_pol(rx)

print("prim_el**34 :",el_1)
print("prim_el**20 :",el_2)
print("prim_el**34 * prim_el**20 :",el)
print("prim_el**54 :",el_3)

# Check if el = el_1
print(el==el_3)

prim_el**34 : x**6 + x**3 + x**2 + x
prim_el**20 : x**7 + x**5 + x**4 + x**2
prim_el**34 * prim_el**20 : x**6 + x**4
prim_el**54 : x**6 + x**4
True

In [41]:
# Tried part (c) while checking if the code is working or not (Low sized fields)

# Question 2

## Define Functions

In [42]:
def gnrt_fnt_fld(d):
    F2_d = {}
    all_coeff = all_coeff_gen(d-1)
    for i in range(0,2**d):
        F2_d[i] = pol_gen(all_coeff[i])
    return F2_d

def fnd_irr_pol(d):
    cnt =0
    irr_pols = {}
    all_coeff = all_coeff_gen(d-1)
    for i in range(0,2**d):
        flag = 0
        sx = x**d + pol_gen(all_coeff[i])
        for j in range (2,2**d): 
            qx,rx= div(sx,pol_gen(all_coeff[j]))
            rx = mod2_pol(rx)  
            if(rx==0):
                flag = 1
                break 
        if(flag==0):
            irr_pols[cnt] = sx
            cnt = cnt + 1
    return irr_pols

def fnd_prim_el(F2_d,sx,d):
    prim_el = 0
    flag = 0
    for i in range(2,2**d):
        if (flag == 0):
            for j in range (1,2**d):
                qx,rx=div((F2_d[i])**(j),sx)
                rx = mod2_pol(rx)
                if (rx == 1):
                    if ( j!= 2**d-1):
                        break
                    elif (j==2**d-1):
                        prim_el = F2_d[i]
                        flag = 1
        else: 
            return prim_el
            break

## Part (a)

In [43]:
# [n = 10 , k = 4] code 
# my = 1 + (prim_el**2)*y 
    
n = 10 

# Field size should be greater than n 
q = 16 

# Generate F2_4
d = 4
F2_4 = gnrt_fnt_fld(d)

irr_pols = fnd_irr_pol(d)
sx = irr_pols[0]
prim_el = fnd_prim_el(F2_4,sx,d)

# Message polynomial takes values from F2_4 (y is a placeholder)
my = 1 + (prim_el**2)*y

In [44]:
print("GF(2^4)")
F2_4

GF(2^4)

{0: 0,
 1: 1,
 2: x,
 3: x + 1,
 4: x**2,
 5: x**2 + 1,
 6: x**2 + x,
 7: x**2 + x + 1,
 8: x**3,
 9: x**3 + 1,
 10: x**3 + x,
 11: x**3 + x + 1,
 12: x**3 + x**2,
 13: x**3 + x**2 + 1,
 14: x**3 + x**2 + x,
 15: x**3 + x**2 + x + 1}

In [45]:
print("All irreducible polynomial of degree 4 over F2:")
irr_pols

All irreducible polynomial of degree 4 over F2:

{0: x**4 + x + 1, 1: x**4 + x**3 + 1, 2: x**4 + x**3 + x**2 + x + 1}

In [46]:
print("Primitive element:", prim_el)

Primitive element: x

In [47]:
print("Message Polynomial:")
my

Message Polynomial:

x**2*y + 1

In [48]:
# Generate codeword 
# Taking first n(=10) elements of the field as evaluation points 
cdwrd = {}
for i in range (0,n):
    qx,rx=div(my.subs(y,F2_4[i]),sx)
    cdwrd[i] = mod2_pol(rx)
print("10-length codeword:")
cdwrd

10-length codeword:

{0: 1,
 1: x**2 + 1,
 2: x**3 + 1,
 3: x**3 + x**2 + 1,
 4: x,
 5: x**2 + x,
 6: x**3 + x,
 7: x**3 + x**2 + x,
 8: x**2 + x + 1,
 9: x + 1}

## Part (b)

In [49]:
# [n = 20 , k = 10] code 
# my = (prim_el**4) + (prim_el**5)*(y**3) + (prim_el**10)*(y**9) 
    
n = 20 

# Field size should be greater than n 
q = 32

# Generate F2_5
d = 5
F2_5 = gnrt_fnt_fld(d)

irr_pols = fnd_irr_pol(d)
sx = irr_pols[0]
prim_el = fnd_prim_el(F2_5,sx,d)

# Message polynomial takes values from F2_5 (y is a placeholder)
my = prim_el**4 + (prim_el**5)*(y**3) + (prim_el**10)*(y**9)

In [50]:
print("GF(2^5)")
F2_5

GF(2^5)

{0: 0,
 1: 1,
 2: x,
 3: x + 1,
 4: x**2,
 5: x**2 + 1,
 6: x**2 + x,
 7: x**2 + x + 1,
 8: x**3,
 9: x**3 + 1,
 10: x**3 + x,
 11: x**3 + x + 1,
 12: x**3 + x**2,
 13: x**3 + x**2 + 1,
 14: x**3 + x**2 + x,
 15: x**3 + x**2 + x + 1,
 16: x**4,
 17: x**4 + 1,
 18: x**4 + x,
 19: x**4 + x + 1,
 20: x**4 + x**2,
 21: x**4 + x**2 + 1,
 22: x**4 + x**2 + x,
 23: x**4 + x**2 + x + 1,
 24: x**4 + x**3,
 25: x**4 + x**3 + 1,
 26: x**4 + x**3 + x,
 27: x**4 + x**3 + x + 1,
 28: x**4 + x**3 + x**2,
 29: x**4 + x**3 + x**2 + 1,
 30: x**4 + x**3 + x**2 + x,
 31: x**4 + x**3 + x**2 + x + 1}

In [51]:
print("All irreducible polynomial of degree 5 over F2:")
irr_pols

All irreducible polynomial of degree 5 over F2:

{0: x**5 + x**2 + 1,
 1: x**5 + x**3 + 1,
 2: x**5 + x**3 + x**2 + x + 1,
 3: x**5 + x**4 + x**2 + x + 1,
 4: x**5 + x**4 + x**3 + x + 1,
 5: x**5 + x**4 + x**3 + x**2 + 1}

In [52]:
print("Primitive element:", prim_el)

Primitive element: x

In [53]:
print("Message Polynomial:")
my

Message Polynomial:

x**10*y**9 + x**5*y**3 + x**4

In [54]:
# Generate codeword 
# Taking first n(=20) elements of the field as evaluation points 
cdwrd = {}
for i in range (0,n):
    qx,rx=div(my.subs(y,F2_5[i]),sx)
    cdwrd[i] = mod2_pol(rx)

print("20-length codeword:")
cdwrd

20-length codeword:

{0: x**4,
 1: x**2,
 2: x**4 + x**3 + x + 1,
 3: x**4 + x**2 + 1,
 4: 1,
 5: x,
 6: x**2 + x,
 7: x**4 + x**3 + x**2 + x + 1,
 8: x**2 + x + 1,
 9: x**3 + x**2 + 1,
 10: x**4 + x**3 + x + 1,
 11: x**3 + x + 1,
 12: x**3,
 13: x**4 + x**2 + 1,
 14: x**4 + x**3,
 15: x**4 + x**3 + x**2 + x + 1,
 16: x**4 + x**3 + x**2,
 17: x**4 + x**2,
 18: x**4 + x**2 + x,
 19: x**2}

## Part (c)

In [55]:
# [n = 50 , k = 25] code 
# my = (prim_el**20) + (prim_el**4)*(y**8) + (prim_el**44)*(y**12) 
#      + (prim_el**30)*(y**14) + (prim_el**15)*(y**18) + (prim_el**3)*(y**23) 
    
n = 50

# Field size should be greater than n 
q = 64

# Generate F2_6
d = 6
F2_6 = gnrt_fnt_fld(d)

irr_pols = fnd_irr_pol(d)
sx = irr_pols[0]
prim_el = fnd_prim_el(F2_6,sx,d)

# Message polynomial takes values from F2_4 (y is a placeholder)
my = (prim_el**20) + (prim_el**4)*(y**8) + (prim_el**44)*(y**12) \
+ (prim_el**30)*(y**14) + (prim_el**15)*(y**18) + (prim_el**3)*(y**23)

In [56]:
print("GF(2^6)")
F2_6

GF(2^6)

{0: 0,
 1: 1,
 2: x,
 3: x + 1,
 4: x**2,
 5: x**2 + 1,
 6: x**2 + x,
 7: x**2 + x + 1,
 8: x**3,
 9: x**3 + 1,
 10: x**3 + x,
 11: x**3 + x + 1,
 12: x**3 + x**2,
 13: x**3 + x**2 + 1,
 14: x**3 + x**2 + x,
 15: x**3 + x**2 + x + 1,
 16: x**4,
 17: x**4 + 1,
 18: x**4 + x,
 19: x**4 + x + 1,
 20: x**4 + x**2,
 21: x**4 + x**2 + 1,
 22: x**4 + x**2 + x,
 23: x**4 + x**2 + x + 1,
 24: x**4 + x**3,
 25: x**4 + x**3 + 1,
 26: x**4 + x**3 + x,
 27: x**4 + x**3 + x + 1,
 28: x**4 + x**3 + x**2,
 29: x**4 + x**3 + x**2 + 1,
 30: x**4 + x**3 + x**2 + x,
 31: x**4 + x**3 + x**2 + x + 1,
 32: x**5,
 33: x**5 + 1,
 34: x**5 + x,
 35: x**5 + x + 1,
 36: x**5 + x**2,
 37: x**5 + x**2 + 1,
 38: x**5 + x**2 + x,
 39: x**5 + x**2 + x + 1,
 40: x**5 + x**3,
 41: x**5 + x**3 + 1,
 42: x**5 + x**3 + x,
 43: x**5 + x**3 + x + 1,
 44: x**5 + x**3 + x**2,
 45: x**5 + x**3 + x**2 + 1,
 46: x**5 + x**3 + x**2 + x,
 47: x**5 + x**3 + x**2 + x + 1,
 48: x**5 + x**4,
 49: x**5 + x**4 + 1,
 50: x**5 + x**4 + x,
 51: x**5 + x**4 + x + 1,
 52: x**5 + x**4 + x**2,
 53: x**5 + x**4 + x**2 + 1,
 54: x**5 + x**4 + x**2 + x,
 55: x**5 + x**4 + x**2 + x + 1,
 56: x**5 + x**4 + x**3,
 57: x**5 + x**4 + x**3 + 1,
 58: x**5 + x**4 + x**3 + x,
 59: x**5 + x**4 + x**3 + x + 1,
 60: x**5 + x**4 + x**3 + x**2,
 61: x**5 + x**4 + x**3 + x**2 + 1,
 62: x**5 + x**4 + x**3 + x**2 + x,
 63: x**5 + x**4 + x**3 + x**2 + x + 1}

In [57]:
print("All irreducible polynomial of degree 5 over F2:")
irr_pols

All irreducible polynomial of degree 5 over F2:

{0: x**6 + x + 1,
 1: x**6 + x**3 + 1,
 2: x**6 + x**4 + x**2 + x + 1,
 3: x**6 + x**4 + x**3 + x + 1,
 4: x**6 + x**5 + 1,
 5: x**6 + x**5 + x**2 + x + 1,
 6: x**6 + x**5 + x**3 + x**2 + 1,
 7: x**6 + x**5 + x**4 + x + 1,
 8: x**6 + x**5 + x**4 + x**2 + 1}

In [58]:
print("Primitive element:", prim_el)

Primitive element: x

In [59]:
print("Message Polynomial:")
my

Message Polynomial:

x**44*y**12 + x**30*y**14 + x**20 + x**15*y**18 + x**4*y**8 + x**3*y**23

In [60]:
# Generate codeword 
# Taking first n(=50) elements of the field as evaluation points 
cdwrd = {}
for i in range (0,n):
    qx,rx=div(my.subs(y,F2_6[i]),sx)
    cdwrd[i] = mod2_pol(rx)

print("50-length codeword:")
cdwrd

50-length codeword:

{0: x**5 + x**4 + x**3 + x**2,
 1: x**4 + x,
 2: x**4 + x**3 + x**2 + x,
 3: x**5 + x**4 + x**3 + 1,
 4: x**5 + x**3 + x**2 + x,
 5: x**4 + x**3 + x**2 + 1,
 6: x**5 + x**4 + x**2 + x,
 7: x**2 + 1,
 8: x**2 + 1,
 9: x**3 + x + 1,
 10: x**5 + x,
 11: x**5 + x**4 + x,
 12: x**5 + x**4 + x**3,
 13: x**4 + 1,
 14: x**2 + x + 1,
 15: x**4 + 1,
 16: x**5 + x + 1,
 17: x**4 + x**3 + x**2 + x + 1,
 18: x**4 + x**3 + x**2,
 19: x**5 + x**3,
 20: x**3 + x + 1,
 21: x**4 + x**3 + x**2 + x,
 22: x**5 + x**4 + x**3 + x**2,
 23: x**5 + x**2 + x,
 24: x**4 + x,
 25: x + 1,
 26: x**3 + x + 1,
 27: x**4 + x**3 + x**2 + 1,
 28: x**5 + x**3 + x**2 + 1,
 29: x**2,
 30: x**2 + 1,
 31: x**2,
 32: x**5 + x**4 + x**2,
 33: x**4 + x**2 + 1,
 34: x**4 + x**3 + x,
 35: x**3 + x**2 + x,
 36: x**3 + x + 1,
 37: x**5 + x**2 + 1,
 38: x**4 + x**2 + x,
 39: x**5 + x**3 + x,
 40: x**5 + x**3 + x**2 + 1,
 41: x**5 + x**2 + x,
 42: x**4 + x**3 + x**2,
 43: x**5 + x**2 + 1,
 44: x**4 + x**3 + x + 1,
 45: x**5 + x**4 + x**3 + x**2 + x + 1,
 46: x**3 + x**2 + x + 1,
 47: x**4 + x**2 + x,
 48: x**4 + x**3 + x**2 + x + 1,
 49: x**5 + x**3 + 1}

# Question 3

In [61]:
def prim_el_rep(el,d,prim_el,sx):
    if (el == 0):
        return "z" 
    for i in range(0,2**d):
        qx,rx = div(prim_el**i,sx)
        temp = mod2_pol(rx)
        if (el == temp):
            return i
        
def prim_el_rep_add(p_1,p_2,d,prim_el,sx):
    if (p_1 !='z' and p_2!='z'):
        temp = prim_el**p_1 + prim_el**p_2
    elif (p_1 == 'z' and p_2!='z'):
        temp = 0 + prim_el**p_2
    elif (p_1 !='z' and p_2 == 'z'):
        temp = prim_el**p_1 + 0
    else:
        temp = 0         
    qx,rx = div(temp,sx)
    return prim_el_rep(mod2_pol(rx),d,prim_el,sx)
    
def prim_el_rep_sub(p_1,p_2,d,prim_el,sx):
    if (p_1 !='z' and p_2!='z'):
        temp = prim_el**p_1 - prim_el**p_2
    elif (p_1 == 'z' and p_2!='z'):
        temp = 0 - prim_el**p_2
    elif (p_1 !='z' and p_2 == 'z'):
        temp = prim_el**p_1 - 0
    else:
        temp = 0         
    qx,rx = div(temp,sx)
    return prim_el_rep(mod2_pol(rx),d,prim_el,sx)

def prim_el_rep_mul(p_1,p_2,d):
    if (p_1 == "z" or p_2 == "z"):
        return "z"
    else:
        return (p_1 + p_2)%(2**d-1)

def prim_el_rep_div(p_1,p_2,d):
    if (p_1 == "z" or p_2 == "z"):
        return "z"
    else:
        return (p_1 - p_2)%(2**d-1) 
    
def prim_el_rep_inverse(p):
    if (p=="z"):
        return "z"
    else:
        return (2**d-1-p)%(2**d-1)

def deg_ny_find(prim_el_rep_ny):
    degr = 0
    for i in range(len(prim_el_rep_ny)):
            if(prim_el_rep_ny[i]!="z"):
                degr = i
    return degr

def pol_from_prim_el_rep(prim_el_rep_vect,var):
    pol_var = 0
    for i in range(len(prim_el_rep_vect)):
        if (prim_el_rep_vect[i]=="z"):
            pol_var = pol_var + 0
        else: 
            pol_var = pol_var + prim_el_rep_vect[i]*var**i
    return pol_var
    

def pol_fq_div(ny,ey,d,prim_el,sx):
    cnt = 0
    prim_el_rep_ny = {}
    for i in range(len(ny)):
        prim_el_rep_ny[i] = prim_el_rep(ny[i],d,prim_el,sx)
    deg_ny = deg_ny_find(prim_el_rep_ny)
    
    prim_el_rep_ey = {}
    for i in range(len(ey)):
        prim_el_rep_ey[i] = prim_el_rep(ey[i],d,prim_el,sx)
    deg_ey = len(ey) - 1     
    qy = 0 
    ry = 0
    
    while(deg_ny>=deg_ey):
        diff = deg_ny - deg_ey
        temp_el = prim_el_rep_ny[deg_ny]
        print("prim_el to the power:",temp_el)
        print("y to the power:",diff)
#         qx,rx = div(prim_el**temp_el,sx)
        qy = qy + (prim_el**temp_el)*y**diff
        for i in range(len(ey)):
            prim_el_rep_ny[diff+i] = prim_el_rep_sub(prim_el_rep_ny[diff+i],prim_el_rep_mul(temp_el,prim_el_rep_ey[i],d),d,prim_el,sx)
        prim_el_rep_ny[deg_ny] = "z"
        deg_ny =  deg_ny_find(prim_el_rep_ny)
    
    ry = pol_from_prim_el_rep(prim_el_rep_ny,y)
    
    return qy,ry

## Part (a)

In [62]:
# [n = 10 , k = 4] code 

n = 10 
k = 4
# Field size should be greater than n 
q = 16 

# Generate F2_4
d = 4
F2_4 = gnrt_fnt_fld(d)

irr_pols = fnd_irr_pol(d)
sx = irr_pols[0]
prim_el = fnd_prim_el(F2_4,sx,d)

In [63]:
# Message polynomial takes values from F2_4 (y is a placeholder)
# my = 1 + (prim_el**2)*y (For example)

my = 0
m_coeff_pow = {}

for i in range(0,k):
    # Take input the power corresponding to primitive element
    # For 0 message coefficient input -1
    m_coeff_pow[i] = int(input())
    if(m_coeff_pow[i] != -1):
        my = my +  prim_el**(m_coeff_pow[i])*y**i

0
2
-1
-1

In [64]:
my

x**2*y + 1

In [67]:
# Generate transmitted codeword 
# Take index of evaluation points as input
eval_points = {}
t_cdwrd = {}

print("Want to give some other evaluation points than first n elements of the field: (y/n)")
inp = input()

if inp == "n":
    for i in range (0,n):
        eval_points[i] = i
        qx,rx=div(my.subs(y,F2_4[eval_points[i]]),sx)
        t_cdwrd[i] = mod2_pol(rx)


elif inp == "y":
    for i in range (0,n):
        eval_points[i] = int(input())
        qx,rx=div(my.subs(y,F2_4[eval_points[i]]),sx)
        t_cdwrd[i] = mod2_pol(rx)
    
print("Transmitted codeword:")
t_cdwrd

Want to give some other evaluation points than first n elements of the field: (y/n)
n
Transmitted codeword:

{0: 1,
 1: x**2 + 1,
 2: x**3 + 1,
 3: x**3 + x**2 + 1,
 4: x,
 5: x**2 + x,
 6: x**3 + x,
 7: x**3 + x**2 + x,
 8: x**2 + x + 1,
 9: x + 1}

In [68]:
d_min = n-k+1
t_err = int ((d_min-1)/2)

print("Minimum distance:", d_min)
print("Correctable errors:", t_err)

Minimum distance: 7
Correctable errors: 3

In [70]:
err_vect_pows = {} 
err_vect = {}
for i in range(0,n):
    # Take input the power corresponding to primitive element
    # For 0 take input -1
    err_vect_pows[i] = int(input())
    if(err_vect_pows[i] != -1):
        qx,rx=div(prim_el**(err_vect_pows[i]),sx)
        err_vect[i] = mod2_pol(rx)
    elif(err_vect_pows[i] == -1):
        err_vect[i] = 0  
print("Error vector:")
err_vect

-1
2
-1
5
-1
-1
-1
-1
-1
-1
Error vector:

{0: 0, 1: x**2, 2: 0, 3: x**2 + x, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0}

In [71]:
# Generate received vector
r_cdwrd = {}
for i in range (0,n):
    r_cdwrd[i] = mod2_pol(t_cdwrd[i] + err_vect[i])
print("Received vector:")
r_cdwrd

Received codeword:

{0: 1,
 1: 1,
 2: x**3 + 1,
 3: x**3 + x + 1,
 4: x,
 5: x**2 + x,
 6: x**3 + x,
 7: x**3 + x**2 + x,
 8: x**2 + x + 1,
 9: x + 1}

## Decoding message polynomial from received vector

In [82]:
# R_cdrwd[i] * E(eval_points[i]) = N(eval_points[i]), i =1,2...n
# n equations in ((t_err)+1)+((t_err+k-1)+1) variables 
# E(y) is t_err degree polynomial so we fix e_t_err=1
# n equations in at most t_err + (t_err + k) <= n variables 
# Coeff_matrix * variables_vector = constant_vector
# Find the solution using gaussian elimination 

# Over F2: -1 = +1 

# First t_err columns of Coeff_matrix correspond to coefficients of E(y)
# Next t_err+k columns of Coeff_matrix correspond to coefficients of N(y)
# i^th row of Coeff_matrix would look like:
# yi,yi*alpha_i,yi*(alpha_i**2),...,yi*(alpha_i**(t_err-1)),1,alpha_i,alpha_i**2,...,alpha_i**(k+t_err-1)

# variables_vector looks like: e_0,e_1,...,e_t_err-1,n_0,n_1,...,n_k+t_err-1

# i^th element of constant_vector would look like: yi*(alpha_i**t_err)

Coeff_matrix = {}
for i in range (0,n):
    Coeff_matrix[i]= {}
    for j in range (0,t_err):
        qx,rx = div(r_cdwrd[i]*(F2_4[eval_points[i]]**j),sx)
        Coeff_matrix[i][j] = mod2_pol(rx)
    for j in range (t_err,k+2*t_err):
        qx,rx = div(F2_4[eval_points[i]]**(j-t_err),sx)
        Coeff_matrix[i][j] = mod2_pol(rx)

constant_vector = {}
for i in range (0,n):
    qx,rx = div(r_cdwrd[i]*(F2_4[eval_points[i]]**t_err),sx)
    constant_vector[i] = mod2_pol(rx)
    
aug_matrix = {}
for i in range(0,n):
    aug_matrix[i] = {}
    for j in range(0,n):
        aug_matrix[i][j]=Coeff_matrix[i][j]
    aug_matrix[i][n] = constant_vector[i]

In [83]:
# Coefficient Matrix
pd.DataFrame(Coeff_matrix).transpose()

,0,1,2,3,4,5,6,7,8,9
0,1,0,0,1,0,0,0,0,0,0
1,1,1,1,1,1,1,1,1,1,1
2,x**3 + 1,1,x,1,x,x**2,x**3,x + 1,x**2 + x,x**3 + x**2
3,x**3 + x + 1,x**3 + x**2 + x,1,1,x + 1,x**2 + 1,x**3 + x**2 + x + 1,x,x**2 + x,x**3 + x
4,x,x**3,x**2 + x,1,x**2,x + 1,x**3 + x**2,x**2 + 1,x**2 + x + 1,x**3 + x**2 + x + 1
5,x**2 + x,x**3 + x**2 + 1,x**3 + x**2,1,x**2 + 1,x,x**3 + x,x**2,x**2 + x + 1,x**3
6,x**3 + x,x**3 + 1,x + 1,1,x**2 + x,x**2 + x + 1,1,x**2 + x,x**2 + x + 1,1
7,x**3 + x**2 + x,x**3 + x**2,x,1,x**2 + x + 1,x**2 + x,1,x**2 + x + 1,x**2 + x,1
8,x**2 + x + 1,x**3 + x**2 + 1,x,1,x**3,x**3 + x**2,x**3 + x,x**3 + x**2 + x + 1,1,x**3
9,x + 1,x**3,x**2,1,x**3 + 1,x**3 + x**2 + 1,x**3 + x**2 + x + 1,x**3 + x**2 + x,x**2 + x + 1,x**3 + x

In [84]:
# Constant Vector
constant_vector

{0: 0,
 1: 1,
 2: x**2,
 3: x + 1,
 4: x**3 + x + 1,
 5: x**3 + 1,
 6: x**3 + x,
 7: x**3 + x**2 + x,
 8: x + 1,
 9: x}

In [85]:
# Augmented Matrix
pd.DataFrame(aug_matrix).transpose()

,0,1,2,3,4,5,6,7,8,9,10
0,1,0,0,1,0,0,0,0,0,0,0
1,1,1,1,1,1,1,1,1,1,1,1
2,x**3 + 1,1,x,1,x,x**2,x**3,x + 1,x**2 + x,x**3 + x**2,x**2
3,x**3 + x + 1,x**3 + x**2 + x,1,1,x + 1,x**2 + 1,x**3 + x**2 + x + 1,x,x**2 + x,x**3 + x,x + 1
4,x,x**3,x**2 + x,1,x**2,x + 1,x**3 + x**2,x**2 + 1,x**2 + x + 1,x**3 + x**2 + x + 1,x**3 + x + 1
5,x**2 + x,x**3 + x**2 + 1,x**3 + x**2,1,x**2 + 1,x,x**3 + x,x**2,x**2 + x + 1,x**3,x**3 + 1
6,x**3 + x,x**3 + 1,x + 1,1,x**2 + x,x**2 + x + 1,1,x**2 + x,x**2 + x + 1,1,x**3 + x
7,x**3 + x**2 + x,x**3 + x**2,x,1,x**2 + x + 1,x**2 + x,1,x**2 + x + 1,x**2 + x,1,x**3 + x**2 + x
8,x**2 + x + 1,x**3 + x**2 + 1,x,1,x**3,x**3 + x**2,x**3 + x,x**3 + x**2 + x + 1,1,x**3,x + 1
9,x + 1,x**3,x**2,1,x**3 + 1,x**3 + x**2 + 1,x**3 + x**2 + x + 1,x**3 + x**2 + x,x**2 + x + 1,x**3 + x,x

In [86]:
aug_matrix_prim_rep = {}
for i in range(0,n):
    aug_matrix_prim_rep[i] = {}
    for j in range(0,n+1):
        aug_matrix_prim_rep[i][j]=prim_el_rep(aug_matrix[i][j],d,prim_el,sx)

In [87]:
# Augmented matrix in terms of powers of pimitive element 
pd.DataFrame(aug_matrix_prim_rep).transpose()

   0   1  2  3   4   5   6   7   8   9   10
0   0   z  z  0   z   z   z   z   z   z   z
1   0   0  0  0   0   0   0   0   0   0   0
2  14   0  1  0   1   2   3   4   5   6   2
3   7  11  0  0   4   8  12   1   5   9   4
4   1   3  5  0   2   4   6   8  10  12   7
5   5  13  6  0   8   1   9   2  10   3  14
6   9  14  4  0   5  10   0   5  10   0   9
7  11   6  1  0  10   5   0  10   5   0  11
8  10  13  1  0   3   6   9  12   0   3   4
9   4   3  2  0  14  13  12  11  10   9   1

In [88]:
# Apply modified(modified arithmetic operations) gaussian elimination algorithm on aug_matrix_prim_rep
# To convert it into row echelon form

# Step 1: Pivot the matrix 
# Step 2: To get the matrix in row echelon form, repeat the pivot

# Find the first non-zero entry in the pivot column(=pivot_row) of the matrix 
for pvt_row in range(0,n):
    row = "NA"
    skip_flag = 0
    
    for i in range (pvt_row,n):
        if (aug_matrix_prim_rep[i][pvt_row] != "z"):
            row = i
            break
    print("row:",row)
    if (row=="NA"):
        skip_flag = 1
        
    
    if(skip_flag==0):    
        print("pvt_row:", pvt_row)
        # Interchange rows, moving the row to the pivot row        
        temp = {}
        temp = aug_matrix_prim_rep[pvt_row]
        aug_matrix_prim_rep[pvt_row] =aug_matrix_prim_rep[row]
        aug_matrix_prim_rep[row] = temp 


        # Multiply each element in the pivot row by the inverse of the pivot, so the pivot equals 1
        pvt_el_inv = prim_el_rep_inverse(aug_matrix_prim_rep[pvt_row][pvt_row])
        for i in range (0,n+1):
            aug_matrix_prim_rep[pvt_row][i] = prim_el_rep_mul(pvt_el_inv,aug_matrix_prim_rep[pvt_row][i],d)

        # Add multiples of the pivot row to each of the lower rows, 
        # so every element in the pivot column of the lower rows equals 0.
        if (aug_matrix_prim_rep[pvt_row][pvt_row] == 'z' and aug_matrix_prim_rep[j][pvt_row] != "z"):
            sys.exit('Divide by zero detected!')

        for j in range(pvt_row+1, n):
            if(aug_matrix_prim_rep[j][pvt_row]=='z'):
                continue
            else:
                ratio = prim_el_rep_div(aug_matrix_prim_rep[j][pvt_row],aug_matrix_prim_rep[pvt_row][pvt_row],d)

            for l in range(0,n+1):
                p_2 = prim_el_rep_mul(ratio,aug_matrix_prim_rep[pvt_row][l],d)
                aug_matrix_prim_rep[j][l]= prim_el_rep_sub(aug_matrix_prim_rep[j][l],p_2,d,prim_el,sx)

row: 0
pvt_row: 0
row: 1
pvt_row: 1
row: 2
pvt_row: 2
row: 3
pvt_row: 3
row: 5
pvt_row: 4
row: 5
pvt_row: 5
row: NA
row: 7
pvt_row: 7
row: 8
pvt_row: 8
row: 9
pvt_row: 9

In [89]:
# row echelon form of aug_matrix_prim_rep
pd.DataFrame(aug_matrix_prim_rep).transpose()

  0  1  2   3   4   5   6   7  8   9   10
0  0  z  z   0   z   z   z   z  z   z   z
1  z  0  0   z   0   0   0   0  0   0   0
2  z  z  0  14   0   4  10  12  6   9   4
3  z  z  z   0  14  12   7   3  z   1  10
4  z  z  z   z   0   3   7   1  9   z  11
5  z  z  z   z   z   0  12   7  3  10   9
6  z  z  z   z   z   z   z  12  5  10  14
7  z  z  z   z   z   z   z   0  2  12   2
8  z  z  z   z   z   z   z   z  0   6   z
9  z  z  z   z   z   z   z   z  z   0   z

In [90]:
# Convert the aug_matrix_prim_rep from row echelon form to row reduced echelon form 

for i in range(n-1,-1,-1):
    pvt_row = "NA"
    # Step 1: Identify the last row having a pivot equal to 1, and let this be the pivot row.
    flg = 0
    for j in range (0,i):
        if (aug_matrix_prim_rep[i][j] != "z"):
            flg = 1
    if ((aug_matrix_prim_rep[i][i] == 0) and (flg == 0)):
            pvt_row = i
            
    if(pvt_row !="NA"):        
        # Step 2: Add multiples of the pivot row to each of the upper rows, 
        # until every element above the pivot equals 0
        if (aug_matrix_prim_rep[pvt_row][pvt_row] == 'z'):
            sys.exit('Divide by zero detected!')

        for j in range(pvt_row-1,-1,-1):
            if(aug_matrix_prim_rep[j][pvt_row]=='z'):
                continue
            else:
                ratio = prim_el_rep_div(aug_matrix_prim_rep[j][pvt_row],aug_matrix_prim_rep[pvt_row][pvt_row],d)

            for l in range(0,n+1):
                p_2 = prim_el_rep_mul(ratio,aug_matrix_prim_rep[pvt_row][l],d)
                aug_matrix_prim_rep[j][l]= prim_el_rep_sub(aug_matrix_prim_rep[j][l],p_2,d,prim_el,sx)

In [91]:
# reduced row echelon form of aug_matrix_prim_rep
pd.DataFrame(aug_matrix_prim_rep).transpose()

  0  1  2  3  4  5   6  7  8  9   10
0  0  z  z  z  z  z   2  z  z  z   1
1  z  0  z  z  z  z  14  z  z  z  11
2  z  z  0  z  z  z  13  z  z  z  13
3  z  z  z  0  z  z   2  z  z  z   1
4  z  z  z  z  0  z   9  z  z  z   5
5  z  z  z  z  z  0  12  z  z  z   z
6  z  z  z  z  z  z   z  z  z  z   z
7  z  z  z  z  z  z   z  0  z  z   2
8  z  z  z  z  z  z   z  z  0  z   z
9  z  z  z  z  z  z   z  z  z  0   z

In [92]:
# First t_err columns of Coeff_matrix correspond to coefficients of E(y)
# Next t_err+k columns of Coeff_matrix correspond to coefficients of N(y)

# Coefficents are stored in polynomial representaion 
Ny = 0
Ey = 0
ny={}
ey ={}

for i in range(0,t_err):
    ey[i] = {}
    if(aug_matrix_prim_rep[i][i] == "z" and aug_matrix_prim_rep[i][n] == "z"):
        # Then let ey[i] be 0 
        ey[i] = 0
    else:
        if(aug_matrix_prim_rep[i][n] == "z"):
            ey[i] = 0
        else:
            qx,rx = div(prim_el**(aug_matrix_prim_rep[i][n]),sx)
            ey[i] = mod2_pol(rx)    
    Ey = Ey + ey[i]*y**(i)    

for i in range(t_err,n):
    ny[i-t_err] = {}
    if(aug_matrix_prim_rep[i][i] == "z" and aug_matrix_prim_rep[i][n] == "z"):
        # Then let ny[i-t_err] be 0  
        ny[i-t_err] = 0
    else:
        if(aug_matrix_prim_rep[i][n] == "z"):
            ny[i-t_err] = 0
        else:
            qx,rx = div(prim_el**(aug_matrix_prim_rep[i][n]),sx)
            ny[ t_err+k-n+i] = mod2_pol(rx)    
    Ny = Ny + ny[i-t_err]*y**(i-t_err)
    
# We had fixed e_t_err=1
ey[t_err] = 1 
Ey = ey[t_err]*y**(t_err)+Ey

In [93]:
ny

{0: x, 1: x**2 + x, 2: 0, 3: 0, 4: x**2, 5: 0, 6: 0}

In [94]:
Ny

x**2*y**4 + x + y*(x**2 + x)

In [95]:
ey

{0: x, 1: x**3 + x**2 + x, 2: x**3 + x**2 + 1, 3: 1}

In [96]:
Ey

x + y**3 + y**2*(x**3 + x**2 + 1) + y*(x**3 + x**2 + x)

In [97]:
my

x**2*y + 1

In [99]:
Ey*my - Ny

-x**2*y**4 - x - y*(x**2 + x) + (x**2*y + 1)*(x + y**3 + y**2*(x**3 + x**2 + 1) + y*(x**3 + x**2 + x))

In [100]:
m_cap_y,ry = pol_fq_div(ny,ey,d,prim_el,sx)

prim_el to the power: 2
y to the power: 1
prim_el to the power: 0
y to the power: 0

In [101]:
m_cap_y

x**2*y + 1

In [102]:
m_cap_y == my

True

## Part (b)

In [103]:
# [n = 20 , k = 10] code 

n = 20
k = 10
# Field size should be greater than n 
q = 32 

# Generate F2_5
d = 5
F2_5 = gnrt_fnt_fld(d)

irr_pols = fnd_irr_pol(d)
sx = irr_pols[0]
prim_el = fnd_prim_el(F2_5,sx,d)

In [104]:
# Message polynomial takes values from F2_5 (y is a placeholder)
# my = (prim_el**4) + (prim_el**5)*(y**3) + (prim_el**10)*(y**9) (For example)

my = 0
m_coeff_pow = {}

for i in range(0,k):
    # Take input the power corresponding to primitive element
    # For 0 message coefficient input -1
    m_coeff_pow[i] = int(input())
    if(m_coeff_pow[i] != -1):
        my = my +  prim_el**(m_coeff_pow[i])*y**i

4
-1
-1
5
-1
-1
-1
-1
-1
10

In [105]:
my

x**10*y**9 + x**5*y**3 + x**4

In [106]:
# Generate transmitted codeword 
# Take index of evaluation points as input
eval_points = {}
t_cdwrd = {}

print("Want to give some other evaluation points than first n elements of the field: (y/n)")
inp = input()

if inp == "n":
    for i in range (0,n):
        eval_points[i] = i
        qx,rx=div(my.subs(y,F2_5[eval_points[i]]),sx)
        t_cdwrd[i] = mod2_pol(rx)


elif inp == "y":
    for i in range (0,n):
        eval_points[i] = int(input())
        qx,rx=div(my.subs(y,F2_5[eval_points[i]]),sx)
        t_cdwrd[i] = mod2_pol(rx)
    
print("Transmitted codeword:")
t_cdwrd

Want to give some other evaluation points than first n elements of the field: (y/n)
n
Transmitted codeword:

{0: x**4,
 1: x**2,
 2: x**4 + x**3 + x + 1,
 3: x**4 + x**2 + 1,
 4: 1,
 5: x,
 6: x**2 + x,
 7: x**4 + x**3 + x**2 + x + 1,
 8: x**2 + x + 1,
 9: x**3 + x**2 + 1,
 10: x**4 + x**3 + x + 1,
 11: x**3 + x + 1,
 12: x**3,
 13: x**4 + x**2 + 1,
 14: x**4 + x**3,
 15: x**4 + x**3 + x**2 + x + 1,
 16: x**4 + x**3 + x**2,
 17: x**4 + x**2,
 18: x**4 + x**2 + x,
 19: x**2}

In [107]:
d_min = n-k+1
t_err = int ((d_min-1)/2)

print("Minimum distance:", d_min)
print("Correctable errors:", t_err)

Minimum distance: 11
Correctable errors: 5

In [109]:
err_vect_pows = {} 
err_vect = {}
for i in range(0,n):
    # Take input the power corresponding to primitive element
    # For 0 take input -1
    err_vect_pows[i] = int(input())
    if(err_vect_pows[i] != -1):
        qx,rx=div(prim_el**(err_vect_pows[i]),sx)
        err_vect[i] = mod2_pol(rx)
    elif(err_vect_pows[i] == -1):
        err_vect[i] = 0  
print("Error vector:")
err_vect

-1
-1
4
4
5
-1
0
-1
-1
-1
-1
1
-1
-1
-1
-1
-1
-1
-1
-1
Error vector:

{0: 0,
 1: 0,
 2: x**4,
 3: x**4,
 4: x**2 + 1,
 5: 0,
 6: 1,
 7: 0,
 8: 0,
 9: 0,
 10: 0,
 11: x,
 12: 0,
 13: 0,
 14: 0,
 15: 0,
 16: 0,
 17: 0,
 18: 0,
 19: 0}

In [110]:
# Generate received vector
r_cdwrd = {}
for i in range (0,n):
    r_cdwrd[i] = mod2_pol(t_cdwrd[i] + err_vect[i])
print("Received vector:")
r_cdwrd

Received codeword:

{0: x**4,
 1: x**2,
 2: x**3 + x + 1,
 3: x**2 + 1,
 4: x**2,
 5: x,
 6: x**2 + x + 1,
 7: x**4 + x**3 + x**2 + x + 1,
 8: x**2 + x + 1,
 9: x**3 + x**2 + 1,
 10: x**4 + x**3 + x + 1,
 11: x**3 + 1,
 12: x**3,
 13: x**4 + x**2 + 1,
 14: x**4 + x**3,
 15: x**4 + x**3 + x**2 + x + 1,
 16: x**4 + x**3 + x**2,
 17: x**4 + x**2,
 18: x**4 + x**2 + x,
 19: x**2}

## Decoding message polynomial from received vector

In [111]:
# R_cdrwd[i] * E(eval_points[i]) = N(eval_points[i]), i =1,2...n
# n equations in ((t_err)+1)+((t_err+k-1)+1) variables 
# E(y) is t_err degree polynomial so we fix e_t_err=1
# n equations in at most t_err + (t_err + k) <= n variables 
# Coeff_matrix * variables_vector = constant_vector
# Find the solution using gaussian elimination 

# Over F2: -1 = +1 

# First t_err columns of Coeff_matrix correspond to coefficients of E(y)
# Next t_err+k columns of Coeff_matrix correspond to coefficients of N(y)
# i^th row of Coeff_matrix would look like:
# yi,yi*alpha_i,yi*(alpha_i**2),...,yi*(alpha_i**(t_err-1)),1,alpha_i,alpha_i**2,...,alpha_i**(k+t_err-1)

# variables_vector looks like: e_0,e_1,...,e_t_err-1,n_0,n_1,...,n_k+t_err-1

# i^th element of constant_vector would look like: yi*(alpha_i**t_err)

Coeff_matrix = {}
for i in range (0,n):
    Coeff_matrix[i]= {}
    for j in range (0,t_err):
        qx,rx = div(r_cdwrd[i]*(F2_5[eval_points[i]]**j),sx)
        Coeff_matrix[i][j] = mod2_pol(rx)
    for j in range (t_err,k+2*t_err):
        qx,rx = div(F2_5[eval_points[i]]**(j-t_err),sx)
        Coeff_matrix[i][j] = mod2_pol(rx)

constant_vector = {}
for i in range (0,n):
    qx,rx = div(r_cdwrd[i]*(F2_5[eval_points[i]]**t_err),sx)
    constant_vector[i] = mod2_pol(rx)
    
aug_matrix = {}
for i in range(0,n):
    aug_matrix[i] = {}
    for j in range(0,n):
        aug_matrix[i][j]=Coeff_matrix[i][j]
    aug_matrix[i][n] = constant_vector[i]

In [112]:
# Coefficient Matrix
pd.DataFrame(Coeff_matrix).transpose()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,x**4,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,x**2,x**2,x**2,x**2,x**2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2,x**3 + x + 1,x**4 + x**2 + x,x**3 + 1,x**4 + x,1,1,x,x**2,x**3,x**4,x**2 + 1,x**3 + x,x**4 + x**2,x**3 + x**2 + 1,x**4 + x**3 + x,x**4 + 1,x**2 + x + 1,x**3 + x**2 + x,x**4 + x**3 + x**2,x**4 + x**3 + x**2 + 1
3,x**2 + 1,x**3 + x**2 + x + 1,x**4 + 1,x**4 + x**2 + x,x**4 + x**3 + x**2 + x + 1,1,x + 1,x**2 + 1,x**3 + x**2 + x + 1,x**4 + 1,x**4 + x**2 + x,x**4 + x**3 + x**2 + x + 1,x**2,x**3 + x**2,x**4 + x**2,x**4 + x**3 + 1,x**3 + x**2 + x,x**4 + x,x**4 + x + 1,x**4
4,x**2,x**4,x**3 + x,x**3 + x**2 + 1,x**4 + 1,1,x**2,x**4,x**3 + x,x**3 + x**2 + 1,x**4 + 1,x**3 + x**2 + x,x**4 + x**3 + x**2 + 1,x**4 + x**3 + x + 1,x + 1,x**3 + x**2,x**4 + x**2 + 1,x**4 + x**3 + x**2 + x,x**4 + x**2 + x + 1,x**4 + x**2 + x
5,x,x**3 + x,x**2 + x + 1,x**4 + x**3 + x + 1,x**4 + x**3,1,x**2 + 1,x**4 + 1,x**4 + x**3 + x**2 + x + 1,x**3 + x**2,x**4 + x**3 + 1,x**4 + x,x**4,x**4 + x**3 + x,x**4 + x**3 + x**2 + 1,x**2 + x,x**4 + x**3 + x**2 + x,x**3 + 1,x**3,x**3 + x**2 + 1
6,x**2 + x + 1,x**4 + x,x + 1,x**3 + x,x**4 + x**3 + 1,1,x**2 + x,x**4 + x**2,x**4 + x**2 + x + 1,x**4 + x**3 + x**2 + 1,x**2,x**4 + x**3,x**4 + x**3 + x,x**4 + x**2 + x,x**4 + x**3 + x + 1,x**4,x**3 + x**2 + x + 1,x**2 + x + 1,x**4 + x,x + 1
7,x**4 + x**3 + x**2 + x + 1,x**4 + x**2 + x + 1,x**3 + x,x**4 + x + 1,x**4 + x**2 + x,1,x**2 + x + 1,x**4 + x**2 + 1,x**2,x**4 + x**3 + x**2,x**4 + x**3 + x**2 + x,x**4,x**4 + x**3 + x**2 + x + 1,x**4 + x**2 + x + 1,x**3 + x,x**4 + x + 1,x**4 + x**2 + x,x**3 + x**2 + 1,x**2 + x,x**4 + x
8,x**2 + x + 1,x**4 + x**3 + x**2 + 1,x**4 + x + 1,x**3 + x**2,x**3 + x**2 + x + 1,1,x**3,x**3 + x,x**4 + x**3 + x,x**3 + x**2 + x,x**4 + x**3 + x**2 + x + 1,x + 1,x**4 + x**3,x**4 + x**3 + x**2 + x,x**3 + x + 1,x**4 + x,x**2,x**2 + 1,x**3 + x**2 + 1,x**2 + x + 1
9,x**3 + x**2 + 1,x**3 + x,x**4,x**2,1,1,x**3 + 1,x**3 + x + 1,x**4 + x**3 + 1,x**3 + x**2 + x + 1,x**4 + x**3,x**2 + x,x**4 + x + 1,x**4 + x**3 + x**2 + x + 1,x**4 + x**3 + x**2,x**2 + x + 1,x**4 + x**3 + x,x**4 + x**2,x**2 + 1,x**3
10,x**4 + x**3 + x + 1,x**4 + x**2 + 1,x**4 + x**2 + x,x**3,x**4 + x**3 + x,1,x**3 + x,x**3 + x**2 + x,x + 1,x**4 + x**3 + x**2 + x,x**4 + x,x**2 + 1,x**2 + x + 1,x**4 + x + 1,x**3 + x**2 + x + 1,x**3 + 1,x**4,x**4 + 1,x**4 + x**3 + x + 1,x**4 + x**2 + 1
11,x**3 + 1,x**4 + x**3 + 1,x**4 + x**3,x**4 + x + 1,x**4 + x**3 + x**2,1,x**3 + x + 1,x**3 + x**2 + x + 1,x**2 + x,x**4 + x**3 + x**2 + x + 1,x**2 + x + 1,x**4 + x**2,x**3,x**4 + x,x**4 + x**2 + x + 1,x**4 + x**2 + 1,x + 1,x**4 + x**3 + x**2 + 1,x**4 + 1,x**3 + x
12,x**3,x**3 + x**2 + x + 1,x**3 + x**2 + x,x,x**4 + x**3,1,x**3 + x**2,x**4 + x**3 + x,x**3 + 1,x + 1,x**4 + x**2,x**3 + x + 1,x**4 + x**3 + x + 1,x**2 + 1,x**4 + x**3 + 1,x**4 + x**3 + x**2 + 1,x**3,x**3 + x**2 + x + 1,x**3 + x**2 + x,x
13,x**4 + x**2 + 1,x**4 + x,x**4 + x**2,x**4 + x**3 + x**2 + x + 1,x**3 + x**2 + x + 1,1,x**3 + x**2 + 1,x**4 + x**3 + x + 1,x**4 + x**3 + x**2 + x,x,x**4 + x**3 + x,x**4 + x + 1,x**4 + x**3 + 1,x**2,x**4 + 1,x + 1,x**4 + x**2 + x + 1,x**3,x**2 + x + 1,x**2 + x
14,x**4 + x**3,x**2,x**4 + x**3 + x**2 + 1,x**4 + x**2 + x + 1,x**4 + x**2,1,x**3 + x**2 + x,x**4 + x**3 + x**2 + x,x**2 + 1,x**4 + x + 1,x**3 + 1,x**4 + 1,x**4 + x**2 + 1,x**3,x**4 + x**3 + x**2 + x + 1,x**3 + x + 1,x**3 + x**2 + 1,x**3 + x**2,x,x**4 + x**3 + x**2
15,x**4 + x**3 + x**2 + x + 1,x**4 + x**2,x**4 + x,x**4 + x**2 + 1,x**4 + x**3 + x**2 + 1,1,x**3 + x**2 + x + 1,x**4 + x**3 + x**2 + x + 1,x**4 + x**2,x**4 + x,x**4 + x**2 + 1,x**4 + x**3 + x**2 + 1,x**3 + x,x**3 + 1,x**4 + x**3,x**4 + x**3 + x**2,x**2 + 1,x**4 + x**2 + x,x**3 + x**2,x**3 + x**2 + x
16,x**4 + x**3 + x**2,x**4 + x + 1,x**4 + x**3,x**4 + x**3 + 1,x**3 + 1,1,x**4,x**3 + x**2 + 1,x**3 + x**2 + x,x**4 + x**3 + x + 1,x**3 + x**2,x**4 + x**3 + x**2 + x,x**4 + x**2 + x,x,x**2 + 1,x**4 + x**3 + x,x**4 + x**3 + x**2,x**4 + x + 1,x**4 + x**3,x**4 + x**3 + 1
17,x**4 + x**2,x**4 + x + 1,x**3 + x + 1,x**3 + x,x**4 + x**3 + x + 1,1,x**4 + 1,x**3 + x**2,x**4 + x,x**4 + x**3 + x,x**2 + x,x**3 + 1,x**3 + x**2 + 1,x + 1,x**4 + x**2 + x,x**4 + x**2,x**4 + x + 1,x**3 + x + 1,x**3 + x,x**4 + x**3 + x + 1
18,x**4 + x**2 + x,x**3 + x + 1,x**4 + x**2 + x + 1,x**4 + x**3 + 1,x**4 + x**3 + x**2 + x,1,x**4 + x,x**3 + 1,x**4 + x**2 + x,x**3 + x + 1,x**4 + x**2 + x + 1,x**4 + x**3 + 1,x**4 + x**3 + x**2 + x,x**3 + x**2 + x + 1,x**4 + x**2 + 1,x**4 + x**3,x**3 + x**2,x**2 + x,x + 1,x**4 + x + 1
19,x**2,x**2 + x,x**2 + 1,x**4 + x**2 + 1,x**3 + x**2 + 1,1,x**4 + x + 1,x**3,x**3 + x**2,x**3 + x,x**3 + x**2 + x + 1,x**4 + x**3 + x,x**4 + x**2 + x + 1,x**3 + x**2 + x,x**3 + 1,x**4 + x**3 + x**2 + x + 1,x,x + 1,x**4,x**4 + x**3

In [113]:
# Constant Vector
constant_vector

{0: 0,
 1: x**2,
 2: x,
 3: x**2,
 4: x**3 + x**2 + x,
 5: x**4 + x**2 + x + 1,
 6: x**4 + x**3 + x**2,
 7: x**3 + x**2 + 1,
 8: x**4 + x**2 + x + 1,
 9: x**3 + 1,
 10: x**4 + x**3 + x**2 + x + 1,
 11: x**4 + x**3 + x,
 12: x**4 + 1,
 13: 1,
 14: x**2 + x,
 15: x**3 + x,
 16: x**2,
 17: x**4 + x**2 + x + 1,
 18: x**3 + x**2 + x + 1,
 19: x**4 + x**3 + 1}

In [114]:
# Augmented Matrix
pd.DataFrame(aug_matrix).transpose()

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,x**4,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,x**2,x**2,x**2,x**2,x**2,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,x**2
2,x**3 + x + 1,x**4 + x**2 + x,x**3 + 1,x**4 + x,1,1,x,x**2,x**3,x**4,...,x**3 + x,x**4 + x**2,x**3 + x**2 + 1,x**4 + x**3 + x,x**4 + 1,x**2 + x + 1,x**3 + x**2 + x,x**4 + x**3 + x**2,x**4 + x**3 + x**2 + 1,x
3,x**2 + 1,x**3 + x**2 + x + 1,x**4 + 1,x**4 + x**2 + x,x**4 + x**3 + x**2 + x + 1,1,x + 1,x**2 + 1,x**3 + x**2 + x + 1,x**4 + 1,...,x**4 + x**3 + x**2 + x + 1,x**2,x**3 + x**2,x**4 + x**2,x**4 + x**3 + 1,x**3 + x**2 + x,x**4 + x,x**4 + x + 1,x**4,x**2
4,x**2,x**4,x**3 + x,x**3 + x**2 + 1,x**4 + 1,1,x**2,x**4,x**3 + x,x**3 + x**2 + 1,...,x**3 + x**2 + x,x**4 + x**3 + x**2 + 1,x**4 + x**3 + x + 1,x + 1,x**3 + x**2,x**4 + x**2 + 1,x**4 + x**3 + x**2 + x,x**4 + x**2 + x + 1,x**4 + x**2 + x,x**3 + x**2 + x
5,x,x**3 + x,x**2 + x + 1,x**4 + x**3 + x + 1,x**4 + x**3,1,x**2 + 1,x**4 + 1,x**4 + x**3 + x**2 + x + 1,x**3 + x**2,...,x**4 + x,x**4,x**4 + x**3 + x,x**4 + x**3 + x**2 + 1,x**2 + x,x**4 + x**3 + x**2 + x,x**3 + 1,x**3,x**3 + x**2 + 1,x**4 + x**2 + x + 1
6,x**2 + x + 1,x**4 + x,x + 1,x**3 + x,x**4 + x**3 + 1,1,x**2 + x,x**4 + x**2,x**4 + x**2 + x + 1,x**4 + x**3 + x**2 + 1,...,x**4 + x**3,x**4 + x**3 + x,x**4 + x**2 + x,x**4 + x**3 + x + 1,x**4,x**3 + x**2 + x + 1,x**2 + x + 1,x**4 + x,x + 1,x**4 + x**3 + x**2
7,x**4 + x**3 + x**2 + x + 1,x**4 + x**2 + x + 1,x**3 + x,x**4 + x + 1,x**4 + x**2 + x,1,x**2 + x + 1,x**4 + x**2 + 1,x**2,x**4 + x**3 + x**2,...,x**4,x**4 + x**3 + x**2 + x + 1,x**4 + x**2 + x + 1,x**3 + x,x**4 + x + 1,x**4 + x**2 + x,x**3 + x**2 + 1,x**2 + x,x**4 + x,x**3 + x**2 + 1
8,x**2 + x + 1,x**4 + x**3 + x**2 + 1,x**4 + x + 1,x**3 + x**2,x**3 + x**2 + x + 1,1,x**3,x**3 + x,x**4 + x**3 + x,x**3 + x**2 + x,...,x + 1,x**4 + x**3,x**4 + x**3 + x**2 + x,x**3 + x + 1,x**4 + x,x**2,x**2 + 1,x**3 + x**2 + 1,x**2 + x + 1,x**4 + x**2 + x + 1
9,x**3 + x**2 + 1,x**3 + x,x**4,x**2,1,1,x**3 + 1,x**3 + x + 1,x**4 + x**3 + 1,x**3 + x**2 + x + 1,...,x**2 + x,x**4 + x + 1,x**4 + x**3 + x**2 + x + 1,x**4 + x**3 + x**2,x**2 + x + 1,x**4 + x**3 + x,x**4 + x**2,x**2 + 1,x**3,x**3 + 1
10,x**4 + x**3 + x + 1,x**4 + x**2 + 1,x**4 + x**2 + x,x**3,x**4 + x**3 + x,1,x**3 + x,x**3 + x**2 + x,x + 1,x**4 + x**3 + x**2 + x,...,x**2 + 1,x**2 + x + 1,x**4 + x + 1,x**3 + x**2 + x + 1,x**3 + 1,x**4,x**4 + 1,x**4 + x**3 + x + 1,x**4 + x**2 + 1,x**4 + x**3 + x**2 + x + 1
11,x**3 + 1,x**4 + x**3 + 1,x**4 + x**3,x**4 + x + 1,x**4 + x**3 + x**2,1,x**3 + x + 1,x**3 + x**2 + x + 1,x**2 + x,x**4 + x**3 + x**2 + x + 1,...,x**4 + x**2,x**3,x**4 + x,x**4 + x**2 + x + 1,x**4 + x**2 + 1,x + 1,x**4 + x**3 + x**2 + 1,x**4 + 1,x**3 + x,x**4 + x**3 + x
12,x**3,x**3 + x**2 + x + 1,x**3 + x**2 + x,x,x**4 + x**3,1,x**3 + x**2,x**4 + x**3 + x,x**3 + 1,x + 1,...,x**3 + x + 1,x**4 + x**3 + x + 1,x**2 + 1,x**4 + x**3 + 1,x**4 + x**3 + x**2 + 1,x**3,x**3 + x**2 + x + 1,x**3 + x**2 + x,x,x**4 + 1
13,x**4 + x**2 + 1,x**4 + x,x**4 + x**2,x**4 + x**3 + x**2 + x + 1,x**3 + x**2 + x + 1,1,x**3 + x**2 + 1,x**4 + x**3 + x + 1,x**4 + x**3 + x**2 + x,x,...,x**4 + x + 1,x**4 + x**3 + 1,x**2,x**4 + 1,x + 1,x**4 + x**2 + x + 1,x**3,x**2 + x + 1,x**2 + x,1
14,x**4 + x**3,x**2,x**4 + x**3 + x**2 + 1,x**4 + x**2 + x + 1,x**4 + x**2,1,x**3 + x**2 + x,x**4 + x**3 + x**2 + x,x**2 + 1,x**4 + x + 1,...,x**4 + 1,x**4 + x**2 + 1,x**3,x**4 + x**3 + x**2 + x + 1,x**3 + x + 1,x**3 + x**2 + 1,x**3 + x**2,x,x**4 + x**3 + x**2,x**2 + x
15,x**4 + x**3 + x**2 + x + 1,x**4 + x**2,x**4 + x,x**4 + x**2 + 1,x**4 + x**3 + x**2 + 1,1,x**3 + x**2 + x + 1,x**4 + x**3 + x**2 + x + 1,x**4 + x**2,x**4 + x,...,x**4 + x**3 + x**2 + 1,x**3 + x,x**3 + 1,x**4 + x**3,x**4 + x**3 + x**2,x**2 + 1,x**4 + x**2 + x,x**3 + x**2,x**3 + x**2 + x,x**3 + x
16,x**4 + x**3 + x**2,x**4 + x + 1,x**4 + x**3,x**4 + x**3 + 1,x**3 + 1,1,x**4,x**3 + x**2 + 1,x**3 + x**2 + x,x**4 + x**3 + x + 1,...,x**4 + x**3 + x**2 + x,x**4 + x**2 + x,x,x**2 + 1,x**4 + x**3 + x,x**4 + x**3 + x**2,x**4 + x + 1,x**4 + x**3,x**4 + x**3 + 1,x**2
17,x**4 + x**2,x**4 + x + 1,x**3 + x + 1,x**3 + x,x**4 + x**3 + x + 1,1,x**4 + 1,x**3 + x**2,x**4 + x,x**4 + x**3 + x,...,x**3 + 1,x**3 + x**2 + 1,x + 1,x**4 + x**2 + x,x**4 + x**2,x**4 + x + 1,x**3 + x + 1,x**3 + x,x**4 + x**3 + x + 1,x**4 + x**2 + x + 1
18,x**4 + x**2 + x,x**3 + x + 1,x**4 + x**2 + x + 1,x**4 + x**3 + 1,x**4 + x**3 + x**2 + x,1,x**4 + x,x**3 + 1,x**4 + x**2 + x,x**3 + x + 1,...,x**4 + x**3 + 1,x**4 + x**3 + x**2 + x,x**3 + x**2 + x + 1,x**4 + x**2 + 1,x**4 + x**3,x**3 + x**2,x**2 + x,x + 1,x**4 + x + 1,x**3 + x**2 + x + 1
19,x**2,x**2 + x,x**2 + 1,x**4 + x**2 + 1,x**3 + x**2 + 1,1,x**4 + x + 1,x**3,x**3 + x**2,x**3 + x,...,x**4 + x**3 + x,x**4 + x**2 + x + 1,x**3 + x**2 + x,x**3 + 1,x**4 + x**3 + x**2 + x + 1,x,x + 1,x**4,x**4 + x**3,x**4 + x**3 + 1

In [115]:
aug_matrix_prim_rep = {}
for i in range(0,n):
    aug_matrix_prim_rep[i] = {}
    for j in range(0,n+1):
        aug_matrix_prim_rep[i][j]=prim_el_rep(aug_matrix[i][j],d,prim_el,sx)

In [116]:
# Augmented matrix in terms of powers of pimitive element 
pd.DataFrame(aug_matrix_prim_rep).transpose()

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,4,z,z,z,z,0,z,z,z,z,...,z,z,z,z,z,z,z,z,z,z
1,2,2,2,2,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
2,27,28,29,30,0,0,1,2,3,4,...,6,7,8,9,10,11,12,13,14,1
3,5,23,10,28,15,0,18,5,23,10,...,15,2,20,7,25,12,30,17,4,2
4,2,4,6,8,10,0,2,4,6,8,...,12,14,16,18,20,22,24,26,28,12
5,1,6,11,16,21,0,5,10,15,20,...,30,4,9,14,19,24,29,3,8,26
6,11,30,18,6,25,0,19,7,26,14,...,21,9,28,16,4,23,11,30,18,13
7,15,26,6,17,28,0,11,22,2,13,...,4,15,26,6,17,28,8,19,30,8
8,11,14,17,20,23,0,3,6,9,12,...,18,21,24,27,30,2,5,8,11,26
9,8,6,4,2,0,0,29,27,25,23,...,19,17,15,13,11,9,7,5,3,29
10,16,22,28,3,9,0,6,12,18,24,...,5,11,17,23,29,4,10,16,22,15
11,29,25,21,17,13,0,27,23,19,15,...,7,3,30,26,22,18,14,10,6,9
12,3,23,12,1,21,0,20,9,29,18,...,27,16,5,25,14,3,23,12,1,10
13,22,30,7,15,23,0,8,16,24,1,...,17,25,2,10,18,26,3,11,19,0
14,21,2,14,26,7,0,12,24,5,17,...,10,22,3,15,27,8,20,1,13,19
15,15,7,30,22,14,0,23,15,7,30,...,14,6,29,21,13,5,28,20,12,6
16,13,17,21,25,29,0,4,8,12,16,...,24,28,1,5,9,13,17,21,25,2
17,7,17,27,6,16,0,10,20,30,9,...,29,8,18,28,7,17,27,6,16,26
18,28,27,26,25,24,0,30,29,28,27,...,25,24,23,22,21,20,19,18,17,23
19,2,19,5,22,8,0,17,3,20,6,...,9,26,12,29,15,1,18,4,21,25

In [117]:
# Apply modified(modified arithmetic operations) gaussian elimination algorithm on aug_matrix_prim_rep
# To convert it into row echelon form

# Step 1: Pivot the matrix 
# Step 2: To get the matrix in row echelon form, repeat the pivot

# Find the first non-zero entry in the pivot column(=pivot_row) of the matrix 
for pvt_row in range(0,n):
    row = "NA"
    skip_flag = 0
    
    for i in range (pvt_row,n):
        if (aug_matrix_prim_rep[i][pvt_row] != "z"):
            row = i
            break
    print("row:",row)
    if (row=="NA"):
        skip_flag = 1
        
    
    if(skip_flag==0):    
        print("pvt_row:", pvt_row)
        # Interchange rows, moving the row to the pivot row        
        temp = {}
        temp = aug_matrix_prim_rep[pvt_row]
        aug_matrix_prim_rep[pvt_row] =aug_matrix_prim_rep[row]
        aug_matrix_prim_rep[row] = temp 


        # Multiply each element in the pivot row by the inverse of the pivot, so the pivot equals 1
        pvt_el_inv = prim_el_rep_inverse(aug_matrix_prim_rep[pvt_row][pvt_row])
        for i in range (0,n+1):
            aug_matrix_prim_rep[pvt_row][i] = prim_el_rep_mul(pvt_el_inv,aug_matrix_prim_rep[pvt_row][i],d)

        # Add multiples of the pivot row to each of the lower rows, 
        # so every element in the pivot column of the lower rows equals 0.
        if (aug_matrix_prim_rep[pvt_row][pvt_row] == 'z' and aug_matrix_prim_rep[j][pvt_row] != "z"):
            sys.exit('Divide by zero detected!')

        for j in range(pvt_row+1, n):
            if(aug_matrix_prim_rep[j][pvt_row]=='z'):
                continue
            else:
                ratio = prim_el_rep_div(aug_matrix_prim_rep[j][pvt_row],aug_matrix_prim_rep[pvt_row][pvt_row],d)

            for l in range(0,n+1):
                p_2 = prim_el_rep_mul(ratio,aug_matrix_prim_rep[pvt_row][l],d)
                aug_matrix_prim_rep[j][l]= prim_el_rep_sub(aug_matrix_prim_rep[j][l],p_2,d,prim_el,sx)

row: 0
pvt_row: 0
row: 1
pvt_row: 1
row: 2
pvt_row: 2
row: 3
pvt_row: 3
row: 4
pvt_row: 4
row: 5
pvt_row: 5
row: 6
pvt_row: 6
row: 7
pvt_row: 7
row: 8
pvt_row: 8
row: 9
pvt_row: 9
row: 10
pvt_row: 10
row: 11
pvt_row: 11
row: 12
pvt_row: 12
row: 13
pvt_row: 13
row: 14
pvt_row: 14
row: 15
pvt_row: 15
row: 16
pvt_row: 16
row: 17
pvt_row: 17
row: 18
pvt_row: 18
row: 19
pvt_row: 19

In [118]:
# row echelon form of aug_matrix_prim_rep
pd.DataFrame(aug_matrix_prim_rep).transpose()

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0,z,z,z,z,27,z,z,z,z,...,z,z,z,z,z,z,z,z,z,z
1,z,0,0,0,0,1,29,29,29,29,...,29,29,29,29,29,29,29,29,29,0
2,z,z,0,18,11,27,7,2,0,27,...,30,3,25,24,4,20,10,12,22,23
3,z,z,z,0,z,17,16,13,5,12,...,10,2,2,22,2,13,8,19,2,11
4,z,z,z,z,0,14,3,24,27,20,...,9,28,28,28,11,21,17,27,23,2
5,z,z,z,z,z,0,15,5,26,7,...,21,11,7,0,6,8,11,22,24,26
6,z,z,z,z,z,z,0,z,9,10,...,27,19,z,24,26,23,12,11,8,25
7,z,z,z,z,z,z,z,0,7,28,...,6,17,29,26,26,11,20,19,20,27
8,z,z,z,z,z,z,z,z,0,30,...,20,22,2,12,25,16,0,3,17,29
9,z,z,z,z,z,z,z,z,z,0,...,13,27,20,11,7,13,13,19,16,z
10,z,z,z,z,z,z,z,z,z,z,...,16,7,17,22,z,14,1,20,6,19
11,z,z,z,z,z,z,z,z,z,z,...,0,z,0,23,14,18,25,15,17,20
12,z,z,z,z,z,z,z,z,z,z,...,z,0,21,16,30,20,13,21,7,5
13,z,z,z,z,z,z,z,z,z,z,...,z,z,0,18,28,0,28,26,21,19
14,z,z,z,z,z,z,z,z,z,z,...,z,z,z,0,18,28,23,1,3,26
15,z,z,z,z,z,z,z,z,z,z,...,z,z,z,z,0,20,12,4,3,11
16,z,z,z,z,z,z,z,z,z,z,...,z,z,z,z,z,0,0,2,29,28
17,z,z,z,z,z,z,z,z,z,z,...,z,z,z,z,z,z,0,28,26,5
18,z,z,z,z,z,z,z,z,z,z,...,z,z,z,z,z,z,z,0,12,29
19,z,z,z,z,z,z,z,z,z,z,...,z,z,z,z,z,z,z,z,0,10

In [119]:
# Convert the aug_matrix_prim_rep from row echelon form to row reduced echelon form 

for i in range(n-1,-1,-1):
    pvt_row = "NA"
    # Step 1: Identify the last row having a pivot equal to 1, and let this be the pivot row.
    flg = 0
    for j in range (0,i):
        if (aug_matrix_prim_rep[i][j] != "z"):
            flg = 1
    if ((aug_matrix_prim_rep[i][i] == 0) and (flg == 0)):
            pvt_row = i
            
    if(pvt_row !="NA"):        
        # Step 2: Add multiples of the pivot row to each of the upper rows, 
        # until every element above the pivot equals 0
        if (aug_matrix_prim_rep[pvt_row][pvt_row] == 'z'):
            sys.exit('Divide by zero detected!')

        for j in range(pvt_row-1,-1,-1):
            if(aug_matrix_prim_rep[j][pvt_row]=='z'):
                continue
            else:
                ratio = prim_el_rep_div(aug_matrix_prim_rep[j][pvt_row],aug_matrix_prim_rep[pvt_row][pvt_row],d)

            for l in range(0,n+1):
                p_2 = prim_el_rep_mul(ratio,aug_matrix_prim_rep[pvt_row][l],d)
                aug_matrix_prim_rep[j][l]= prim_el_rep_sub(aug_matrix_prim_rep[j][l],p_2,d,prim_el,sx)

In [120]:
# reduced row echelon form of aug_matrix_prim_rep
pd.DataFrame(aug_matrix_prim_rep).transpose()

   0  1  2  3  4  5  6  7  8  9   ... 11 12 13 14 15 16 17 18 19  20
0   0  z  z  z  z  z  z  z  z  z  ...  z  z  z  z  z  z  z  z  z   5
1   z  0  z  z  z  z  z  z  z  z  ...  z  z  z  z  z  z  z  z  z  30
2   z  z  0  z  z  z  z  z  z  z  ...  z  z  z  z  z  z  z  z  z  12
3   z  z  z  0  z  z  z  z  z  z  ...  z  z  z  z  z  z  z  z  z   0
4   z  z  z  z  0  z  z  z  z  z  ...  z  z  z  z  z  z  z  z  z   3
5   z  z  z  z  z  0  z  z  z  z  ...  z  z  z  z  z  z  z  z  z   9
6   z  z  z  z  z  z  0  z  z  z  ...  z  z  z  z  z  z  z  z  z   3
7   z  z  z  z  z  z  z  0  z  z  ...  z  z  z  z  z  z  z  z  z  16
8   z  z  z  z  z  z  z  z  0  z  ...  z  z  z  z  z  z  z  z  z   0
9   z  z  z  z  z  z  z  z  z  0  ...  z  z  z  z  z  z  z  z  z   2
10  z  z  z  z  z  z  z  z  z  z  ...  z  z  z  z  z  z  z  z  z  18
11  z  z  z  z  z  z  z  z  z  z  ...  0  z  z  z  z  z  z  z  z   5
12  z  z  z  z  z  z  z  z  z  z  ...  z  0  z  z  z  z  z  z  z   8
13  z  z  z  z  z  z  z  z  z  z  ...  z  z  0  z  z  z  z  z  z   5
14  z  z  z  z  z  z  z  z  z  z  ...  z  z  z  0  z  z  z  z  z  15
15  z  z  z  z  z  z  z  z  z  z  ...  z  z  z  z  0  z  z  z  z   9
16  z  z  z  z  z  z  z  z  z  z  ...  z  z  z  z  z  0  z  z  z  22
17  z  z  z  z  z  z  z  z  z  z  ...  z  z  z  z  z  z  0  z  z  10
18  z  z  z  z  z  z  z  z  z  z  ...  z  z  z  z  z  z  z  0  z  13
19  z  z  z  z  z  z  z  z  z  z  ...  z  z  z  z  z  z  z  z  0  10

[20 rows x 21 columns]

In [121]:
# First t_err columns of Coeff_matrix correspond to coefficients of E(y)
# Next t_err+k columns of Coeff_matrix correspond to coefficients of N(y)

# Coefficents are stored in polynomial representaion 
Ny = 0
Ey = 0
ny={}
ey ={}

for i in range(0,t_err):
    ey[i] = {}
    if(aug_matrix_prim_rep[i][i] == "z" and aug_matrix_prim_rep[i][n] == "z"):
        # Then let ey[i] be 0 
        ey[i] = 0
    else:
        if(aug_matrix_prim_rep[i][n] == "z"):
            ey[i] = 0
        else:
            qx,rx = div(prim_el**(aug_matrix_prim_rep[i][n]),sx)
            ey[i] = mod2_pol(rx)    
    Ey = Ey + ey[i]*y**(i)    

for i in range(t_err,n):
    ny[i-t_err] = {}
    if(aug_matrix_prim_rep[i][i] == "z" and aug_matrix_prim_rep[i][n] == "z"):
        # Then let ny[i-t_err] be 0  
        ny[i-t_err] = 0
    else:
        if(aug_matrix_prim_rep[i][n] == "z"):
            ny[i-t_err] = 0
        else:
            qx,rx = div(prim_el**(aug_matrix_prim_rep[i][n]),sx)
            ny[ t_err+k-n+i] = mod2_pol(rx)    
    Ny = Ny + ny[i-t_err]*y**(i-t_err)
    
# We had fixed e_t_err=1
ey[t_err] = 1 
Ey = ey[t_err]*y**(t_err)+Ey

In [122]:
ny

{0: x**4 + x**3 + x,
 1: x**3,
 2: x**4 + x**3 + x + 1,
 3: 1,
 4: x**2,
 5: x + 1,
 6: x**2 + 1,
 7: x**3 + x**2 + 1,
 8: x**2 + 1,
 9: x**4 + x**3 + x**2 + x + 1,
 10: x**4 + x**3 + x,
 11: x**4 + x**2 + 1,
 12: x**4 + 1,
 13: x**4 + x**3 + x**2,
 14: x**4 + 1}

In [123]:
Ny

x**4 + x**3*y + x**3 + x**2*y**4 + x + y**14*(x**4 + 1) + y**13*(x**4 + x**3 + x**2) + y**12*(x**4 + 1) + y**11*(x**4 + x**2 + 1) + y**10*(x**4 + x**3 + x) + y**9*(x**4 + x**3 + x**2 + x + 1) + y**8*(x**2 + 1) + y**7*(x**3 + x**2 + 1) + y**6*(x**2 + 1) + y**5*(x + 1) + y**3 + y**2*(x**4 + x**3 + x + 1)

In [124]:
ey

{0: x**2 + 1, 1: x**4 + x, 2: x**3 + x**2 + x, 3: 1, 4: x**3, 5: 1}

In [125]:
Ey

x**3*y**4 + x**2 + y**5 + y**3 + y**2*(x**3 + x**2 + x) + y*(x**4 + x) + 1

In [126]:
my

x**10*y**9 + x**5*y**3 + x**4

In [127]:
Ey*my - Ny

-x**4 - x**3*y - x**3 - x**2*y**4 - x - y**14*(x**4 + 1) - y**13*(x**4 + x**3 + x**2) - y**12*(x**4 + 1) - y**11*(x**4 + x**2 + 1) - y**10*(x**4 + x**3 + x) - y**9*(x**4 + x**3 + x**2 + x + 1) - y**8*(x**2 + 1) - y**7*(x**3 + x**2 + 1) - y**6*(x**2 + 1) - y**5*(x + 1) - y**3 - y**2*(x**4 + x**3 + x + 1) + (x**10*y**9 + x**5*y**3 + x**4)*(x**3*y**4 + x**2 + y**5 + y**3 + y**2*(x**3 + x**2 + x) + y*(x**4 + x) + 1)

In [128]:
m_cap_y,ry = pol_fq_div(ny,ey,d,prim_el,sx)

prim_el to the power: 10
y to the power: 9
prim_el to the power: 5
y to the power: 3
prim_el to the power: 4
y to the power: 0

In [129]:
m_cap_y

x**10*y**9 + x**5*y**3 + x**4

In [130]:
m_cap_y == my

True

## Part (c)

In [ ]:
# [n = 50 , k = 20] code 
    
n = 50 
k = 20
# Field size should be greater than n 
q = 64 

# Generate F2_6
d = 6
F2_6 = gnrt_fnt_fld(d)

irr_pols = fnd_irr_pol(d)
sx = irr_pols[0]
prim_el = fnd_prim_el(F2_6,sx,d)

In [ ]:
# AVOIDING [n = 50 , k = 20] CODE AS THERE WOULD BE LOTS OF INPUTS TO GIVE AS CODE LENGTH IS LARGE(50)
# AND OPREESIONS LIKE GAUSSIAN ELIMINATION WOULD TAKE A LOT OF TIME TO RUN

# Problem 4

## Define Functions

In [428]:
def sp_gaus_elim(aug_matrix_prim_rep,n,cmcolnum):
# Apply modified(modified arithmetic operations) gaussian elimination algorithm on aug_matrix_prim_rep

# To convert it into row echelon form
# Step 1: Pivot the matrix 
# Note: As the number of variables are more than the number of equations pivot might not be at i,i 
# Step 2: To get the matrix in row echelon form, repeat the pivot

# Find the first non-zero entry in the pivot column(!=pivot_row) of the matrix 
    pvt_col = 0
    pvt_row = 0
    while (pvt_row < n or pvt_col < cmcolnum):
#         print (aug_matrix_prim_rep)
        print("pvt_col:",pvt_col)
        row = "NA"
        skip_flag = 0

        for i in range (pvt_row,n):
            if (aug_matrix_prim_rep[i][pvt_col] != "z"):
                row = i
                break
        print("row:",row)
        if (row=="NA"):
            skip_flag = 1
            pvt_col = pvt_col+1


        if(skip_flag==0):    
            print("pvt_row:", pvt_row)
            # Interchange rows, moving the row to the pivot row        
            temp = {}
            temp = aug_matrix_prim_rep[pvt_row]
            aug_matrix_prim_rep[pvt_row] =aug_matrix_prim_rep[row]
            aug_matrix_prim_rep[row] = temp 


            # Multiply each element in the pivot row by the inverse of the pivot, so the pivot equals 1
            pvt_el_inv = prim_el_rep_inverse(aug_matrix_prim_rep[pvt_row][pvt_col])
            for i in range (0,cmcolnum+1):
                aug_matrix_prim_rep[pvt_row][i] = prim_el_rep_mul(pvt_el_inv,aug_matrix_prim_rep[pvt_row][i],d)

            # Add multiples of the pivot row to each of the lower rows, 
            # so every element in the pivot column of the lower rows equals 0.

            for j in range(pvt_row+1, n):
                if(aug_matrix_prim_rep[j][pvt_col]=='z'):
                    continue
                else:
                    ratio = prim_el_rep_div(aug_matrix_prim_rep[j][pvt_col],aug_matrix_prim_rep[pvt_row][pvt_col],d)

                for l in range(0,cmcolnum+1):
                    p_2 = prim_el_rep_mul(ratio,aug_matrix_prim_rep[pvt_row][l],d)
                    aug_matrix_prim_rep[j][l]= prim_el_rep_sub(aug_matrix_prim_rep[j][l],p_2,d,prim_el,sx)
            pvt_col = pvt_col + 1
            pvt_row = pvt_row + 1
            
def sp_rre_form(aug_matrix_prim_rep,n,cmcolnum):
# Convert the aug_matrix_prim_rep from row echelon form to row reduced echelon form 
    for i in range(0,n):
        for j in range(0,cmcolnum):
            if(aug_matrix_prim_rep[i][j]==0):
                for l in range(0,i):
                    aug_matrix_prim_rep[l][j]="z"
                break

In [227]:
# degx_qxy  = sqrt(n*(k-1))
# degy_qxy  = sqrt(n/(k-1)) 
degy_qxy = 3 

# n/(k-1) = 9 implies n = 9(k-1)
# therefore degx_qxy  = 3*(k-1)
# Let k = 2 
# therefore n = 9
degx_qxy = 3

In [235]:
# [n = 12 , k = 4] code     
n = 9
k = 2
# Field size should be greater than n 
q = 16

# Generate F2_4
d = 4
F2_4 = gnrt_fnt_fld(d)

irr_pols = fnd_irr_pol(d)
sx = irr_pols[0]
prim_el = fnd_prim_el(F2_4,sx,d)
e_max = n - 2*degx_qxy -1
print("e_max:",e_max)

e_max: 2

In [236]:
# Message polynomial takes values from F2_4 (y is a placeholder)
# mX = 1 + (prim_el**2)*X 
mX = 0
m_coeff_pow = {}

for i in range(0,k):
    # Take input the power corresponding to primitive element
    # For 0 message coefficient input -1
    m_coeff_pow[i] = int(input())
    if(m_coeff_pow[i] != -1):
        mX = mX +  prim_el**(m_coeff_pow[i])*X**i

0
2

In [237]:
mX

X*x**2 + 1

In [238]:
# Generate transmitted codeword 
# Take index of evaluation points as input
eval_points = {}
t_cdwrd = {}

print("Want to give some other evaluation points than first n elements of the field: (y/n)")
inp = input()

if inp == "n":
    for i in range (0,n):
        eval_points[i] = i
        qx,rx=div(mX.subs(X,F2_4[eval_points[i]]),sx)
        t_cdwrd[i] = mod2_pol(rx)


elif inp == "y":
    for i in range (0,n):
        eval_points[i] = int(input())
        qx,rx=div(mX.subs(X,F2_4[eval_points[i]]),sx)
        t_cdwrd[i] = mod2_pol(rx)
    
print("Transmitted codeword:")
t_cdwrd

Want to give some other evaluation points than first n elements of the field: (y/n)
n
Transmitted codeword:

{0: 1,
 1: x**2 + 1,
 2: x**3 + 1,
 3: x**3 + x**2 + 1,
 4: x,
 5: x**2 + x,
 6: x**3 + x,
 7: x**3 + x**2 + x,
 8: x**2 + x + 1}

In [239]:
d_min = n-k+1
print("Minimum distance:", d_min)

Minimum distance: 8

In [240]:
err_vect_pows = {} 
err_vect = {}
for i in range(0,n):
    # Take input the power corresponding to primitive element
    # For 0 take input -1
    err_vect_pows[i] = int(input())
    if(err_vect_pows[i] != -1):
        qx,rx=div(prim_el**(err_vect_pows[i]),sx)
        err_vect[i] = mod2_pol(rx)
    elif(err_vect_pows[i] == -1):
        err_vect[i] = 0  
print("Error vector:")
err_vect

0
0
-1
-1
-1
-1
-1
-1
-1
Error vector:

{0: 1, 1: 1, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0}

In [241]:
# Generate received vector 
r_cdwrd = {}
for i in range (0,n):
    r_cdwrd[i] = mod2_pol(t_cdwrd[i] + err_vect[i])
print("Received vector:")
r_cdwrd

Received vector:

{0: 0,
 1: x**2,
 2: x**3 + 1,
 3: x**3 + x**2 + 1,
 4: x,
 5: x**2 + x,
 6: x**3 + x,
 7: x**3 + x**2 + x,
 8: x**2 + x + 1}

### STEP I: Interpolation step

In [429]:
# Q(X,Y) = sum(i from 0 to degx_qxy) sum(j from 0 to degy_qxy) q_ij*X^i*Y^j

# Q(eval_points[l],r_cdrwd[l])=0 for l =1,2...n
# n equations in (degx_qxy+1)*(degy_qxy+1) variables

# Coeff_matrix * variables_vector = constant_vector

# l^th row of Coeff_matrix would look like:
# y_l^0*alpha_l^0, y_l^0*alpha_l^1,...,y_l^0*alpha_l^b,...,y_l^a*alpha_l^0, y_l^a*alpha_l^1,...,y_l^a*alpha_l^b

# variables_vector looks like: q_00,q_01,...,q_0b,...,q_a0,q_a1,...,q_ab

# Constant vector is an n-lenght 0 vector 

a = degx_qxy
b = degy_qxy
cmcolnum = (a+1)*(b+1)

Coeff_matrix = {}
for l in range (0,n):
    cnt = 0
    Coeff_matrix[l]= {}
    for i in range (0,a+1):
        for j in range (0,b+1):
            qx,rx = div((r_cdwrd[l]**i)*(F2_4[eval_points[l]]**j),sx)
            Coeff_matrix[l][cnt] = mod2_pol(rx)
            cnt = cnt + 1 

constant_vector = {}
for i in range (0,cmcolnum):
    constant_vector[i] = 0
    
aug_matrix = {}
for i in range(0,n):
    aug_matrix[i] = {}
    for j in range(0,cmcolnum):
        aug_matrix[i][j]= Coeff_matrix[i][j]
    aug_matrix[i][cmcolnum] = constant_vector[i]

In [430]:
pd.set_option("display.max_rows", None, "display.max_columns", None)
# Coefficient Matrix
pd.DataFrame(Coeff_matrix).transpose()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,1,1,1,x**2,x**2,x**2,x**2,x + 1,x + 1,x + 1,x + 1,x**3 + x**2,x**3 + x**2,x**3 + x**2,x**3 + x**2
2,1,x,x**2,x**3,x**3 + 1,1,x,x**2,x**3 + x**2 + 1,x**3 + 1,1,x,x**3 + x**2 + x + 1,x**3 + x**2 + 1,x**3 + 1,1
3,1,x + 1,x**2 + 1,x**3 + x**2 + x + 1,x**3 + x**2 + 1,x**2,x**3 + x**2,x**2 + x + 1,x**3 + x**2 + x,1,x + 1,x**2 + 1,x**3 + x,x**3 + x**2 + 1,x**2,x**3 + x**2
4,1,x**2,x + 1,x**3 + x**2,x,x**3,x**2 + x,x**3 + x + 1,x**2,x + 1,x**3 + x**2,x**2 + 1,x**3,x**2 + x,x**3 + x + 1,x**3 + x
5,1,x**2 + 1,x,x**3 + x,x**2 + x,x**3 + x**2 + 1,x**3 + x**2,x**3 + 1,x**2 + x + 1,x**3,x**3 + x**2 + x,x + 1,1,x**2 + 1,x,x**3 + x
6,1,x**2 + x,x**2 + x + 1,1,x**3 + x,x**3 + 1,x + 1,x**3 + x,x**3,x**2 + 1,x**3 + x**2 + 1,x**3,x**3 + x**2 + x + 1,x**2,x**3 + x + 1,x**3 + x**2 + x + 1
7,1,x**2 + x + 1,x**2 + x,1,x**3 + x**2 + x,x**3 + x**2,x,x**3 + x**2 + x,x**3 + x + 1,x**2,x**3 + x**2 + x + 1,x**3 + x + 1,x**3,x**3 + x**2 + 1,x**2 + 1,x**3
8,1,x**3,x**3 + x**2,x**3 + x,x**2 + x + 1,x**3 + x**2 + 1,x,x + 1,x**2 + x,x**2 + 1,x**3 + x**2 + x,x**3 + 1,1,x**3,x**3 + x**2,x**3 + x

In [431]:
# Constant Vector
constant_vector

{0: 0,
 1: 0,
 2: 0,
 3: 0,
 4: 0,
 5: 0,
 6: 0,
 7: 0,
 8: 0,
 9: 0,
 10: 0,
 11: 0,
 12: 0,
 13: 0,
 14: 0,
 15: 0}

In [432]:
# Augmented Matrix
pd.DataFrame(aug_matrix).transpose()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,1,1,1,x**2,x**2,x**2,x**2,x + 1,x + 1,x + 1,x + 1,x**3 + x**2,x**3 + x**2,x**3 + x**2,x**3 + x**2,0
2,1,x,x**2,x**3,x**3 + 1,1,x,x**2,x**3 + x**2 + 1,x**3 + 1,1,x,x**3 + x**2 + x + 1,x**3 + x**2 + 1,x**3 + 1,1,0
3,1,x + 1,x**2 + 1,x**3 + x**2 + x + 1,x**3 + x**2 + 1,x**2,x**3 + x**2,x**2 + x + 1,x**3 + x**2 + x,1,x + 1,x**2 + 1,x**3 + x,x**3 + x**2 + 1,x**2,x**3 + x**2,0
4,1,x**2,x + 1,x**3 + x**2,x,x**3,x**2 + x,x**3 + x + 1,x**2,x + 1,x**3 + x**2,x**2 + 1,x**3,x**2 + x,x**3 + x + 1,x**3 + x,0
5,1,x**2 + 1,x,x**3 + x,x**2 + x,x**3 + x**2 + 1,x**3 + x**2,x**3 + 1,x**2 + x + 1,x**3,x**3 + x**2 + x,x + 1,1,x**2 + 1,x,x**3 + x,0
6,1,x**2 + x,x**2 + x + 1,1,x**3 + x,x**3 + 1,x + 1,x**3 + x,x**3,x**2 + 1,x**3 + x**2 + 1,x**3,x**3 + x**2 + x + 1,x**2,x**3 + x + 1,x**3 + x**2 + x + 1,0
7,1,x**2 + x + 1,x**2 + x,1,x**3 + x**2 + x,x**3 + x**2,x,x**3 + x**2 + x,x**3 + x + 1,x**2,x**3 + x**2 + x + 1,x**3 + x + 1,x**3,x**3 + x**2 + 1,x**2 + 1,x**3,0
8,1,x**3,x**3 + x**2,x**3 + x,x**2 + x + 1,x**3 + x**2 + 1,x,x + 1,x**2 + x,x**2 + 1,x**3 + x**2 + x,x**3 + 1,1,x**3,x**3 + x**2,x**3 + x,0

In [433]:
aug_matrix_prim_rep = {}
for i in range(0,n):
    aug_matrix_prim_rep[i] = {}
    for j in range(0,cmcolnum+1):
        aug_matrix_prim_rep[i][j]=prim_el_rep(aug_matrix[i][j],d,prim_el,sx)

In [434]:
# Augmented matrix in terms of powers of pimitive element 
pd.DataFrame(aug_matrix_prim_rep).transpose()

  0   1   2   3   4   5  6   7   8   9   10  11  12  13  14  15 16
0  0   z   z   z   z   z  z   z   z   z   z   z   z   z   z   z  z
1  0   0   0   0   2   2  2   2   4   4   4   4   6   6   6   6  z
2  0   1   2   3  14   0  1   2  13  14   0   1  12  13  14   0  z
3  0   4   8  12  13   2  6  10  11   0   4   8   9  13   2   6  z
4  0   2   4   6   1   3  5   7   2   4   6   8   3   5   7   9  z
5  0   8   1   9   5  13  6  14  10   3  11   4   0   8   1   9  z
6  0   5  10   0   9  14  4   9   3   8  13   3  12   2   7  12  z
7  0  10   5   0  11   6  1  11   7   2  12   7   3  13   8   3  z
8  0   3   6   9  10  13  1   4   5   8  11  14   0   3   6   9  z

In [435]:
sp_gaus_elim(aug_matrix_prim_rep,n,cmcolnum)

pvt_col: 0
row: 0
pvt_row: 0
pvt_col: 1
row: 1
pvt_row: 1
pvt_col: 2
row: 2
pvt_row: 2
pvt_col: 3
row: 3
pvt_row: 3
pvt_col: 4
row: 4
pvt_row: 4
pvt_col: 5
row: 5
pvt_row: 5
pvt_col: 6
row: NA
pvt_col: 7
row: 6
pvt_row: 6
pvt_col: 8
row: NA
pvt_col: 9
row: NA
pvt_col: 10
row: NA
pvt_col: 11
row: 7
pvt_row: 7
pvt_col: 12
row: NA
pvt_col: 13
row: NA
pvt_col: 14
row: NA
pvt_col: 15
row: 8
pvt_row: 8

In [436]:
# row echelon form of aug_matrix_prim_rep
pd.DataFrame(aug_matrix_prim_rep).transpose()

  0  1  2  3   4   5  6  7  8  9   10  11  12  13  14  15 16
0  0  z  z  z   z   z  z  z  z  z   z   z   z   z   z   z  z
1  z  0  0  0   2   2  2  2  4  4   4   4   6   6   6   6  z
2  z  z  0  4  10   9  4  1  2  7   5  12  12   0  11   4  z
3  z  z  z  0   z  10  4  5  z  2  10  12   9   1  10  10  z
4  z  z  z  z   0   2  2  z  0  2  10   3  11  10  13   5  z
5  z  z  z  z   z   0  0  0  z  0   0   1  10   5   9  14  z
6  z  z  z  z   z   z  z  0  z  z   2   7   z   4  11   4  z
7  z  z  z  z   z   z  z  z  z  z   z   0   z   z   2   8  z
8  z  z  z  z   z   z  z  z  z  z   z   z   z   z   z   0  z

In [437]:
sp_rre_form(aug_matrix_prim_rep,n,cmcolnum)

In [438]:
# reduced row echelon form of aug_matrix_prim_rep
pd.DataFrame(aug_matrix_prim_rep).transpose()

  0  1  2  3  4  5  6  7  8  9   10 11  12  13  14 15 16
0  0  z  z  z  z  z  z  z  z  z   z  z   z   z   z  z  z
1  z  0  z  z  z  z  2  z  4  4   4  z   6   6   6  z  z
2  z  z  0  z  z  z  4  z  2  7   5  z  12   0  11  z  z
3  z  z  z  0  z  z  4  z  z  2  10  z   9   1  10  z  z
4  z  z  z  z  0  z  2  z  0  2  10  z  11  10  13  z  z
5  z  z  z  z  z  0  0  z  z  0   0  z  10   5   9  z  z
6  z  z  z  z  z  z  z  0  z  z   2  z   z   4  11  z  z
7  z  z  z  z  z  z  z  z  z  z   z  0   z   z   2  z  z
8  z  z  z  z  z  z  z  z  z  z   z  z   z   z   z  0  z

In [452]:
# In F2: -1 = +1
# Coefficents are stored in polynomial representaion 

qxy = {}

for i in range(0,cmcolnum):
    qxy[i]=0

const_col = cmcolnum
for j in range(cmcolnum-1,-1,-1):
    if(aug_matrix_prim_rep[n-1][j]!=0):
        const_col = j
        qxy[const_col] = 1
        break 

for i in range(0,n):
    for j in range(i,const_col):
        if(aug_matrix_prim_rep[i][j]==0):
            if(aug_matrix_prim_rep[i][const_col] == "z"):
                qxy[j] = 0
            else:
                qx,rx = div(prim_el**(aug_matrix_prim_rep[i][const_col]),sx)
                qxy[j] = mod2_pol(rx)
            break

In [453]:
qxy

{0: 0,
 1: x**3 + x**2,
 2: x**3 + x**2 + x,
 3: x**2 + x + 1,
 4: x**3 + x**2 + 1,
 5: x**3 + x,
 6: 0,
 7: x**3 + x**2 + x,
 8: 0,
 9: 0,
 10: 0,
 11: x**2,
 12: 0,
 13: 0,
 14: 1,
 15: 0}

In [469]:
# Verify whether qxy is a correct solution or not
err_flag = 0
for i in range (0,n):
    summ = 0
    for j in range (0,cmcolnum):
        if (aug_matrix_prim_rep[i][j] !="z"):
            summ = summ + prim_el**(aug_matrix_prim_rep[i][j])*qxy[j]
    qx,rx = div(summ,sx)
    if (mod2_pol(rx)!=0):
        err_flag = 1
err_flag

0

In [470]:
Q_XY = 0
cnt = 0
for i in range (0,a+1):
        for j in range (0,b+1):
            Q_XY = Q_XY + qxy[cnt]*(X**i)*(Y**j)
            cnt = cnt + 1

In [471]:
Q_XY

X**3*Y**2 + X**2*Y**3*x**2 + X*Y**3*(x**3 + x**2 + x) + X*Y*(x**3 + x) + X*(x**3 + x**2 + 1) + Y**3*(x**2 + x + 1) + Y**2*(x**3 + x**2 + x) + Y*(x**3 + x**2)

In [472]:
mX

X*x**2 + 1

In [473]:
# Not part of the decoding process just for checking purpose

#Substitute Y = mX to check if Q_XY is correct Q_X(Y=mX) should be zero 
Q_XY.subs(Y,mX)

X**3*(X*x**2 + 1)**2 + X**2*x**2*(X*x**2 + 1)**3 + X*(x**3 + x)*(X*x**2 + 1) + X*(X*x**2 + 1)**3*(x**3 + x**2 + x) + X*(x**3 + x**2 + 1) + (x**3 + x**2)*(X*x**2 + 1) + (X*x**2 + 1)**3*(x**2 + x + 1) + (X*x**2 + 1)**2*(x**3 + x**2 + x)